@tool
## working_nodes_codegen.gd
## Converts a Working Nodes graph (serialized Dictionary) into:
##   • VG code  (.vg)  — executes in the VisualGasic interpreter
##   • 2D scene (.tscn) + companion .vg script
##   • 3D scene (.tscn) + companion .vg script
##
## All public methods are static so they can be called without an instance.
class_name working_nodes_codegen
extends RefCounted


# ─── Public API ──────────────────────────────────────────────────────────────

## Generate VG code from a Working Nodes graph dictionary.
## data  – the parsed JSON dict (from a .wnodes save).
## Returns the full VG code as a String.
static func generate_vg_code(data: Dictionary) -> String:
	var gen := _VGGen.new()
	return gen.build(data)


## Generate a Godot 2D scene (.tscn text) from a Working Nodes graph.
## vg_script_path – the res:// path where the companion .vg file will be saved.
## root_type     – the Godot node type for the root (default "Node2D").
## Returns the TSCN file content as a String.
static func generate_scene_2d_tscn(data: Dictionary, vg_script_path: String, root_type: String = "Node2D") -> String:
	var gen := _SceneGen.new()
	return gen.build_2d(data, vg_script_path, root_type)


## Generate a Godot 3D scene (.tscn text) from a Working Nodes graph.
## vg_script_path – the res:// path where the companion .vg file will be saved.
## root_type     – the Godot node type for the root (default "Node3D").
## Returns the TSCN file content as a String.
static func generate_scene_3d_tscn(data: Dictionary, vg_script_path: String, root_type: String = "Node3D") -> String:
	var gen := _SceneGen.new()
	return gen.build_3d(data, vg_script_path, root_type)


## Generate a GDScript (.gd) source file from a Working Nodes graph.
## Returns the full GDScript source as a String.
static func generate_gdscript(data: Dictionary) -> String:
	var gen := _GDScriptGen.new()
	return gen.build(data)


## Parse VG code (.vg source) back into a Working Nodes graph dictionary.
## Returns a dict compatible with the editor's _apply_loaded_data / _rebuild_node_from_dict.
static func parse_vg_to_graph_data(vg_code: String) -> Dictionary:
	var parser := _VGParser.new()
	return parser.parse(vg_code)


## Derive a clean identifier (no spaces, starts with letter) from a raw string.
static func sanitize_name(raw: String, fallback: String = "Node") -> String:
	var out := ""
	for i in raw.length():
		var c := raw[i]
		if c.is_valid_identifier() or (i > 0 and c >= "0" and c <= "9"):
			out += c
		elif c == " " or c == "_":
			out += "_"
	if out.is_empty():
		return fallback
	if out[0] >= "0" and out[0] <= "9":
		out = "_" + out
	return out


# ─── VG Code Generator ───────────────────────────────────────────────────────

class _VGGen:
	var _nodes: Dictionary = {}     # node_name -> node_dict
	var _conns: Array = []          # connection dicts
	var _groups: Dictionary = {}    # group_id -> group_dict
	var _lines: PackedStringArray = PackedStringArray()

	func build(data: Dictionary) -> String:
		_nodes = {}
		_conns = []
		_groups = {}
		_lines = PackedStringArray()

		# ── Normalise node list ───────────────────────────────────────────
		for nd in data.get("nodes", []):
			var n_name: String = str(nd.get("name", nd.get("title", "WN_0")))
			# Prefer "kind" (fallback editor) over "type" (simple editor)
			var n_kind: String = str(nd.get("kind", nd.get("type", "action"))).capitalize()
			var entry: Dictionary = nd.duplicate()
			entry["_kind"] = n_kind
			entry["_name"] = n_name
			_nodes[n_name] = entry

		_conns = data.get("connections", [])
		_groups = {}
		for g in data.get("groups", []):
			_groups[int(g.get("id", 0))] = g

		# ── Header comment ────────────────────────────────────────────────
		_w("' Generated by Working Nodes — VisualGasic")
		_w("' Edit this file in the VG Code Editor, then press Run to execute.")
		_w("'")
		_w("' This script calls into wn_runtime.vg (WN_Move, WN_Rotate, …).")
		_w("' Keep wn_runtime.vg in the same folder as this file — the Working")
		_w("' Nodes 'Run Graph' button copies it there automatically.")
		_w("")

		# ── Variable declarations ─────────────────────────────────────────
		var var_nodes := _nodes_of_kind("Variable")
		if not var_nodes.is_empty():
			_w("' --- Variables ---")
			for nd in var_nodes:
				_emit_variable_decl(nd)
			_w("")

		# ── Math helper functions (top-level, called from event subs) ─────
		var math_nodes := _nodes_of_kind("Math")
		var bm_nodes   := _nodes_of_kind("Boolmath")
		var vm_nodes   := _nodes_of_kind("Vectormath")
		var mr_nodes   := _nodes_of_kind("Maprange")
		var rv_nodes   := _nodes_of_kind("Randomvalue")
		var cmp_nodes  := _nodes_of_kind("Compare")

		if not (math_nodes + bm_nodes + vm_nodes + mr_nodes + rv_nodes + cmp_nodes).is_empty():
			_w("' --- Math / Utility Functions ---")
			for nd in math_nodes:   _emit_math_function(nd)
			for nd in bm_nodes:     _emit_boolmath_function(nd)
			for nd in vm_nodes:     _emit_vectormath_function(nd)
			for nd in mr_nodes:     _emit_maprange_function(nd)
			for nd in rv_nodes:     _emit_randomvalue_function(nd)
			for nd in cmp_nodes:    _emit_compare_function(nd)
			_w("")

		# ── User-defined functions ────────────────────────────────────────
		var fn_nodes := _nodes_of_kind("Function")
		if not fn_nodes.is_empty():
			_w("' --- Custom Functions ---")
			for nd in fn_nodes:
				_emit_function_node(nd)
			_w("")

		# ── Event handlers ────────────────────────────────────────────────
		# Simple editor uses lowercase "event"; fallback uses "Event"
		# Trigger-style editor uses "on_start" → capitalized to "On Start"
		# "On Input" nodes are merged into a single Sub Form_KeyDown to avoid
		# duplicate sub names when multiple On Input nodes exist in the graph.
		var event_kinds := ["Event", "Timedevent", "Collisiontrigger", "On Start",
							"On Frame", "On Collision"]
		var event_nodes: Array = []
		for kind in event_kinds:
			event_nodes.append_array(_nodes_of_kind(kind))
		var input_nodes: Array = _nodes_of_kind("On Input")

		if event_nodes.is_empty() and input_nodes.is_empty():
			# No explicit event nodes — wrap all actions in Form_Load
			_w("Sub Form_Load()")
			_w("    ' No Event nodes found; all actions placed here.")
			var all_actions := _nodes_of_kind("Action") + _nodes_of_kind("Trigger")
			for nd in all_actions:
				_emit_action_call(nd, "    ")
			_w("End Sub")
		else:
			for nd in event_nodes:
				_emit_event_sub(nd)
			# Merge all On Input nodes into one Sub Form_KeyDown
			if not input_nodes.is_empty():
				_emit_merged_input_sub(input_nodes)

		# ── Action subs (implementations) ────────────────────────────────
		var action_kinds := [
			"Action", "Trigger", "Movegroup", "Rotategroup", "Spawntrigger",
			"Alphafade", "Togglegroup", "Pulseeffect", "Followtarget",
			"Cameracontrol", "Colorchannel",
			# New trigger-style action types:
			"Move", "Rotate", "Scale", "Alpha", "Color Trigger",
			"Pulse", "Spawn", "Stop", "Toggle", "Follow",
			"Shake", "Play Sfx", "Animate",
		]
		var action_nodes: Array = []
		for kind in action_kinds:
			action_nodes.append_array(_nodes_of_kind(kind))

		if not action_nodes.is_empty():
			_w("")
			_w("' --- Action Implementations ---")
			for nd in action_nodes:
				_emit_action_sub(nd)

		# ── Condition helpers ─────────────────────────────────────────────
		var cond_nodes := _nodes_of_kind("Condition") + _nodes_of_kind("Switch")
		if not cond_nodes.is_empty():
			_w("")
			_w("' --- Condition Helpers ---")
			for nd in cond_nodes:
				_emit_condition_sub(nd)

		# ── Loop subs ─────────────────────────────────────────────────────
		var loop_nodes := _nodes_of_kind("Loop")
		if not loop_nodes.is_empty():
			_w("")
			_w("' --- Loop Helpers ---")
			for nd in loop_nodes:
				_emit_loop_sub(nd)

		return "\n".join(Array(_lines))

	# ─── Helpers ─────────────────────────────────────────────────────────────

	func _w(line: String) -> void:
		_lines.append(line)

	func _nodes_of_kind(kind: String) -> Array:
		var out: Array = []
		var lk := kind.to_lower()
		for n in _nodes.values():
			if str(n.get("_kind", "")).to_lower() == lk:
				out.append(n)
		return out

	func _safe_name(nd: Dictionary, fallback: String = "WNNode") -> String:
		var raw := str(nd.get("title", nd.get("_name", fallback)))
		return working_nodes_codegen.sanitize_name(raw, fallback)

	## Return a list of node dicts connected *from* node_name on any port.
	func _downstream_of(node_name: String) -> Array:
		var out: Array = []
		for c in _conns:
			if str(c.get("from", "")) == node_name:
				var tn := str(c.get("to", ""))
				if _nodes.has(tn):
					out.append(_nodes[tn])
		return out

	## Topological walk from an entry node; returns ordered list of nodes.
	func _exec_chain(start_name: String) -> Array:
		var ordered: Array = []
		var visited: Dictionary = {}
		var queue: Array = [start_name]
		while not queue.is_empty():
			var cur: String = queue.pop_front()
			if visited.has(cur):
				continue
			visited[cur] = true
			if _nodes.has(cur):
				ordered.append(_nodes[cur])
			for c in _conns:
				if str(c.get("from", "")) == cur:
					queue.push_back(str(c.get("to", "")))
		return ordered

	# ─── Variable declaration ─────────────────────────────────────────────────

	func _emit_variable_decl(nd: Dictionary) -> void:
		var vname := str(nd.get("var_name", _safe_name(nd, "myVar")))
		var vtype := str(nd.get("var_type", "Double"))
		var vg_type := _map_type(vtype)
		var title := str(nd.get("title", vname))
		_w("Dim " + vname + " As " + vg_type + "  ' Variable node: " + title)

	func _map_type(t: String) -> String:
		match t.to_lower():
			"float", "double": return "Double"
			"int", "integer":  return "Long"
			"bool", "boolean": return "Boolean"
			"string":          return "String"
			"vector2":         return "String"   # VG uses String for vectors
			"vector3":         return "String"
			"color":           return "String"
			_: return "Variant"

	# ─── Event sub ───────────────────────────────────────────────────────────

	func _emit_event_sub(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var ev_type := str(nd.get("event_type", nd.get("title", "On Start")))
		var sub_sig := _event_signature(ev_type, n_name)
		_w("")
		_w("' Event: " + str(nd.get("title", n_name)))
		_w(sub_sig)

		# Walk execution chain and emit calls
		var chain := _exec_chain(n_name)
		var indent := "    "
		for linked_nd in chain:
			if str(linked_nd.get("_name", "")) == n_name:
				continue
			var kind := str(linked_nd.get("_kind", "")).to_lower()
			match kind:
				"variable":
					pass  # already declared at top
				"condition":
					_emit_inline_condition(linked_nd, indent)
				"loop":
					_emit_inline_loop(linked_nd, indent)
				"sequence":
					_emit_inline_sequence(linked_nd, indent)
				"branch":
					_emit_inline_branch(linked_nd, indent)
				"cmp trig":
					_emit_inline_cmp_trig(linked_nd, indent)
				"input poll":
					_emit_inline_input_poll(linked_nd, indent)
				"math", "boolmath", "vectormath", "maprange", "randomvalue", "compare":
					pass  # called via function; only emit if result is used
				_:
					_emit_action_call(linked_nd, indent)

		_w("End Sub")

	# ─── Merged On Input sub ─────────────────────────────────────────────────
	# Multiple On Input nodes must share a single Sub Form_KeyDown to avoid
	# duplicate sub names.  Each node's key becomes an If / ElseIf guard.

	func _emit_merged_input_sub(input_nodes: Array) -> void:
		_w("")
		_w("' On Input: handles key events from all On Input nodes")
		_w("Sub Form_KeyDown(ByVal key As String)")
		var indent := "    "
		var is_first := true
		for nd in input_nodes:
			var n_name  := str(nd.get("_name", "WN_0"))
			var prm: Dictionary = nd.get("params", {})
			# Key param can be nested dict {"Key":"space"} or flat {"Key":"space"}
			var raw_key := str(prm.get("Key", prm.get("key", "space")))
			var key_lbl := raw_key.to_lower()
			var keyword := "ElseIf"
			if is_first:
				keyword = "If"
				is_first = false
			_w(indent + keyword + " key = \"" + key_lbl + "\" Then")
			var chain := _exec_chain(n_name)
			for linked_nd in chain:
				if str(linked_nd.get("_name", "")) == n_name:
					continue
				var kind := str(linked_nd.get("_kind", "")).to_lower()
				match kind:
					"variable":
						pass
					"condition":
						_emit_inline_condition(linked_nd, indent + "    ")
					"loop":
						_emit_inline_loop(linked_nd, indent + "    ")
					"sequence":
						_emit_inline_sequence(linked_nd, indent + "    ")
					"branch":
						_emit_inline_branch(linked_nd, indent + "    ")
					"cmp trig":
						_emit_inline_cmp_trig(linked_nd, indent + "    ")
					"input poll":
						_emit_inline_input_poll(linked_nd, indent + "    ")
					"math", "boolmath", "vectormath", "maprange", "randomvalue", "compare":
						pass
					_:
						_emit_action_call(linked_nd, indent + "    ")
		if not is_first:
			_w(indent + "End If")
		_w("End Sub")

	func _event_signature(ev_type: String, n_name: String) -> String:
		var t := ev_type.to_lower()
		if "start" in t or "ready" in t or "load" in t:
			return "Sub Form_Load()"
		elif "process" in t or "update" in t or "frame" in t:
			return "Sub Form_Process(ByVal delta As Single)"  # runs every physics frame
		elif "timer" in t:
			return "Sub Timer1_Tick()"
		elif t == "on input":
			return "Sub Form_KeyDown(ByVal key As String)"
		elif "touch" in t or "click" in t or "input" in t:
			return "Sub Form_Click()"
		elif "signal" in t:
			return "Sub Form_Signal(ByVal signal_name As String)"
		elif "collision" in t:
			return "Sub Form_Collision(ByVal other As String)"
		elif "timed" in t:
			return "Sub WN_" + n_name.replace("WN_", "") + "_Tick()"
		else:
			var safe := working_nodes_codegen.sanitize_name(ev_type, "WNEvent")
			return "Sub " + safe + "_Event()"

	# ─── Inline condition ─────────────────────────────────────────────────────

	func _emit_inline_condition(nd: Dictionary, indent: String) -> void:
		var cmp_op := str(nd.get("compare_op", "=="))
		var cmp_val := str(nd.get("compare_value", "0"))
		var var_a := str(nd.get("var_a", "value"))
		_w(indent + "If " + var_a + " " + cmp_op + " " + cmp_val + " Then")
		var true_chain := _downstream_of(str(nd.get("_name", "")))
		for tn in true_chain:
			_emit_action_call(tn, indent + "    ")
		_w(indent + "End If")

	# ─── Inline loop ──────────────────────────────────────────────────────────

	func _emit_inline_loop(nd: Dictionary, indent: String) -> void:
		var count := int(nd.get("loop_count", nd.get("params", {}).get("Count", 3)))
		var loop_type := str(nd.get("loop_type", nd.get("params", {}).get("Type", "For (count)"))).to_lower()
		var prm: Dictionary = nd.get("params", {})
		if "for" in loop_type and "each" not in loop_type:
			_w(indent + "Dim _i As Long")
			_w(indent + "For _i = 0 To " + str(count - 1) + " Step 1")
			var body_chain := _downstream_of(str(nd.get("_name", "")))
			for bn in body_chain:
				_emit_action_call(bn, indent + "    ")
			_w(indent + "Next _i")
		elif "while" in loop_type:
			# Honour explicit Condition param when present (default True keeps
			# back-compatible behaviour but emits a Break-on-counter sentinel).
			var cond := str(nd.get("condition", prm.get("Condition", ""))).strip_edges()
			if cond.is_empty():
				cond = "True"
			_w(indent + "Do While " + cond + "  ' loop node: " + str(nd.get("title", "")))
			var wbody := _downstream_of(str(nd.get("_name", "")))
			for bn in wbody:
				_emit_action_call(bn, indent + "    ")
			if cond == "True":
				_w(indent + "    Exit Do  ' safety: remove or replace with a real break")
			_w(indent + "Loop")
		elif "each" in loop_type:
			var src := str(nd.get("source_array", prm.get("Source_Array", prm.get("Array", "")))).strip_edges()
			if src.is_empty():
				src = "arr"
			# Strip any trailing () the user may have typed.
			if src.ends_with("()"):
				src = src.substr(0, src.length() - 2)
			_w(indent + "Dim _item As Variant")
			_w(indent + "For Each _item In " + src + "()")
			var ebody := _downstream_of(str(nd.get("_name", "")))
			for bn in ebody:
				_emit_action_call(bn, indent + "    ")
			_w(indent + "Next _item")

	# ─── Inline sequence ──────────────────────────────────────────────────────

	func _emit_inline_sequence(nd: Dictionary, indent: String) -> void:
		var prm  := nd.get("params", {})
		var intv := str(prm.get("Interval", "0.0"))
		_w(indent + "' Sequence: " + str(nd.get("title", "")) + "  (interval=" + intv + ")")
		var outputs := _downstream_of(str(nd.get("_name", "")))
		for i in outputs.size():
			var dn: Dictionary = outputs[i]
			if float(intv) > 0.0:
				_w(indent + "Call WN_Wait(" + str(float(intv) * i) + ")")
			_w(indent + "' Step " + str(i + 1) + ":")
			_emit_action_call(dn, indent)

	func _emit_inline_branch(nd: Dictionary, indent: String) -> void:
		var prm     := nd.get("params", {})
		var counter := str(prm.get("Counter", "score"))
		var op      := str(prm.get("Op",      ">="))
		var val     := str(prm.get("Value",   "0"))
		var n_name  := str(nd.get("_name", ""))
		_w(indent + "If " + counter + " " + _to_vg_op(op) + " " + val + " Then")
		for dn in _downstream_by_port(n_name, 0):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "Else")
		for dn in _downstream_by_port(n_name, 1):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "End If")

	func _emit_inline_cmp_trig(nd: Dictionary, indent: String) -> void:
		var prm    := nd.get("params", {})
		var a_name := str(prm.get("A",  "score"))
		var op     := str(prm.get("Op", ">"))
		var b_name := str(prm.get("B",  "0"))
		var n_name := str(nd.get("_name", ""))
		_w(indent + "If " + a_name + " " + _to_vg_op(op) + " " + b_name + " Then")
		for dn in _downstream_by_port(n_name, 0):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "Else")
		for dn in _downstream_by_port(n_name, 1):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "End If")

	func _to_vg_op(op: String) -> String:
		match op:
			"==": return "="
			"!=": return "<>"
			">=": return ">="
			"<=": return "<="
			">": return ">"
			"<": return "<"
			_:   return op

	func _downstream_by_port(node_name: String, from_port: int) -> Array:
		var out: Array = []
		for c in _conns:
			if str(c.get("from", "")) == node_name and int(c.get("from_port", 0)) == from_port:
				var tn := str(c.get("to", ""))
				if _nodes.has(tn):
					out.append(_nodes[tn])
		return out

	# ─── Value-wire helpers ───────────────────────────────────────────────────

	## Ordered param keys per trigger kind (matches slot_offset + index).
	## Used by _resolve_param to look up which slot corresponds to a param key.
	const _TRIGGER_PARAM_ORDER: Dictionary = {
		"move":          ["Group_ID", "X", "Y", "Duration", "Easing"],
		"rotate":        ["Group_ID", "Degrees", "Duration", "Lock_Rot"],
		"scale":         ["Group_ID", "Scale_X", "Scale_Y", "Duration"],
		"alpha":         ["Group_ID", "Alpha", "Duration"],
		"color trigger": ["Channel", "R", "G", "B", "Duration"],
		"pulse":         ["Group_ID", "R", "G", "B", "Fade_In", "Hold", "Fade_Out"],
		"spawn":         ["Group_ID", "Delay"],
		"stop":          ["Group_ID"],
		"toggle":        ["Group_ID", "Active"],
		"follow":        ["Group_ID", "Target_Group", "X_Mod", "Y_Mod", "Duration"],
		"shake":         ["Strength", "Interval", "Duration"],
		"play sfx":      ["Sound", "Volume", "Pitch"],
		"animate":       ["Group_ID", "Animation", "Speed"],
		"counter":       ["Name", "Op", "Value"],
		"random trig":   ["Min", "Max", "Store_To"],
		"timer":         ["Delay", "Repeat"],
		"zoom":          ["Zoom", "Duration"],
		"camera move":   ["Target_Group", "Duration", "X_Offset", "Y_Offset"],
		"get prop":      ["Node_Path", "Property", "Store_To"],
		"set prop":      ["Node_Path", "Property", "Value"],
		"input poll":    ["Action", "Mode"],
		"expr":          ["Store_To", "Expression"],
		"delta var":     ["Var", "Op", "Rate"],
	}

	## Returns the exec-flow slot offset for a trigger kind.
	## Kinds with an else-out port start params at slot 2; all others at slot 1.
	func _slot_offset_for_kind(kind: String) -> int:
		match kind:
			"branch", "cmp trig", "input poll": return 2
			_: return 1

	## Builds an inline VG expression for a Math node's operation.
	func _math_inline_expr(a: String, b: String, op: String) -> String:
		match op:
			"add":                return "(%s + %s)" % [a, b]
			"subtract":           return "(%s - %s)" % [a, b]
			"multiply":           return "(%s * %s)" % [a, b]
			"divide":             return "(IIF(%s <> 0, %s / %s, 0))" % [b, a, b]
			"min":                return "IIF(%s < %s, %s, %s)" % [a, b, a, b]
			"max":                return "IIF(%s > %s, %s, %s)" % [a, b, a, b]
			"modulo":             return "(%s Mod %s)" % [a, b]
			"power":              return "(%s ^ %s)" % [a, b]
			"abs", "absolute":    return "Abs(%s)" % a
			"floor":              return "Int(%s)" % a
			"round":              return "CLng(%s)" % a
			"sine", "sin":        return "Sin(%s)" % a
			"cosine", "cos":      return "Cos(%s)" % a
			_:                    return "(%s + %s)" % [a, b]

	## Returns an inline VG expression for any value wire arriving at (to_name, to_slot).
	## Returns "" when no wire is connected.  Recursively resolves chained math nodes.
	func _value_wire_expr(to_name: String, to_slot: int) -> String:
		for c in _conns:
			if str(c.get("to", "")) != to_name or int(c.get("to_port", -1)) != to_slot:
				continue
			var from_name := str(c.get("from", ""))
			if not _nodes.has(from_name):
				continue
			var src: Dictionary = _nodes[from_name]
			var src_kind := str(src.get("_kind", "")).to_lower()
			var prm: Dictionary = src.get("params", {})
			if src_kind == "math":
				# Recursively resolve A and B (handles chained math nodes)
				var a_expr := _value_wire_expr(from_name, 1)
				if a_expr.is_empty():
					a_expr = str(prm.get("A", "0"))
				var b_expr := _value_wire_expr(from_name, 2)
				if b_expr.is_empty():
					b_expr = str(prm.get("B", "0"))
				var op := str(prm.get("OpSelect", prm.get("math_op", "add"))).to_lower()
				return _math_inline_expr(a_expr, b_expr, op)
			elif src_kind == "get_prop" or src_kind == "get prop":
				# get_prop node output — emit GetNode("path").property inline
				var path := str(prm.get("Node_Path", ""))
				var prop  := str(prm.get("Property",  ""))
				if not path.is_empty() and not prop.is_empty():
					return "GetNode(\"%s\").%s" % [path, prop]
		return ""

	## Returns either a value-wire inline expression (if a Math node feeds this param)
	## or the literal string from the params dict.
	func _resolve_param(nd: Dictionary, prm: Dictionary, key: String, default: String) -> String:
		var n_name := str(nd.get("_name", ""))
		var kind   := str(nd.get("_kind", "")).to_lower()
		var order: Array = _TRIGGER_PARAM_ORDER.get(kind, [])
		var idx := order.find(key)
		if idx >= 0:
			var wire := _value_wire_expr(n_name, _slot_offset_for_kind(kind) + idx)
			if not wire.is_empty():
				return wire
		return str(prm.get(key, default))

	func _emit_inline_input_poll(nd: Dictionary, indent: String) -> void:
		var prm    := nd.get("params", {})
		var action := str(prm.get("Action", "move_right"))
		var mode   := str(prm.get("Mode",   "pressed")).to_lower()
		var n_name := str(nd.get("_name", ""))
		var vg_fn  := "IsActionPressed"
		if "just_pressed" in mode or "just pressed" in mode:
			vg_fn = "IsActionJustPressed"
		elif "just_released" in mode or "just released" in mode:
			vg_fn = "IsActionJustReleased"
		_w(indent + "If Input." + vg_fn + "(\"" + action + "\") Then")
		for dn in _downstream_by_port(n_name, 0):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "Else")
		for dn in _downstream_by_port(n_name, 1):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "End If")

	func _emit_inline_delta_var(nd: Dictionary, indent: String) -> void:
		var prm   := nd.get("params", {})
		var vname := str(prm.get("Var",  "velY"))
		var op    := str(prm.get("Op",   "+=" ))
		var rate  := str(prm.get("Rate", "980"))
		match op:
			"+=": _w(indent + vname + " = " + vname + " + " + rate + " * delta")
			"-=": _w(indent + vname + " = " + vname + " - " + rate + " * delta")
			"*=": _w(indent + vname + " = " + vname + " * " + rate + " * delta")
			"=":  _w(indent + vname + " = " + rate + " * delta")
			_:   _w(indent + vname + " = " + vname + " + " + rate + " * delta")

	func _emit_action_call(nd: Dictionary, indent: String) -> void:
		# Breakpoint probe
		if nd.get("_breakpoint", false):
			_w(indent + "Print \">>> BREAKPOINT: " + str(nd.get("title", str(nd.get("_name","?")))) + "\"")
		var kind := str(nd.get("_kind", "")).to_lower()
		var n_name := str(nd.get("_name", "WN_0"))
		match kind:
			"action":
				var sub_n := "Action_" + n_name
				_w(indent + "Call " + sub_n + "()")
			"movegroup":
				var gid := str(nd.get("group_id", 1))
				var mx  := str(nd.get("move_x",  0))
				var my  := str(nd.get("move_y",  0))
				var dur := str(nd.get("duration", 0.0))
				_w(indent + "Call WN_MoveGroup(" + gid + ", " + mx + ", " + my + ", " + dur + ")")
			"rotategroup":
				var gid := str(nd.get("group_id", 1))
				var deg := str(nd.get("degrees",  0))
				var dur := str(nd.get("duration", 0.0))
				_w(indent + "Call WN_RotateGroup(" + gid + ", " + deg + ", " + dur + ")")
			"spawntrigger":
				var tgt := str(nd.get("target_group", 1))
				var delay := str(nd.get("delay", 0.0))
				_w(indent + "Call WN_SpawnTrigger(" + tgt + ", " + delay + ")")
			"alphafade":
				var gid := str(nd.get("group_id", 1))
				var opa := str(nd.get("opacity",  1.0))
				var dur := str(nd.get("duration", 0.5))
				_w(indent + "Call WN_AlphaFade(" + gid + ", " + opa + ", " + dur + ")")
			"togglegroup":
				var gid  := str(nd.get("group_id", 1))
				var mode := str(nd.get("toggle_mode", "Toggle On"))
				_w(indent + "Call WN_ToggleGroup(" + gid + ", \"" + mode + "\")")
			"colorchannel":
				var ch  := str(nd.get("channel", 1))
				var dur := str(nd.get("duration", 0.5))
				_w(indent + "Call WN_ColorChannel(" + ch + ", dur:=" + dur + ")")
			"pulseeffect":
				var gid := str(nd.get("group_id", 1))
				var fi  := str(nd.get("fade_in",  0.1))
				var hld := str(nd.get("hold",     0.2))
				var fo  := str(nd.get("fade_out", 0.1))
				_w(indent + "Call WN_PulseEffect(" + gid + ", " + fi + ", " + hld + ", " + fo + ")")
			"followtarget":
				var gid := str(nd.get("group_id",     1))
				var tgt := str(nd.get("target_group", 2))
				var spd := str(nd.get("x_speed",      100.0))
				_w(indent + "Call WN_FollowTarget(" + gid + ", " + tgt + ", " + spd + ")")
			"cameracontrol":
				var op  := str(nd.get("cam_op",  "Zoom"))
				var val := str(nd.get("value",   1.0))
				var dur := str(nd.get("duration", 0.5))
				_w(indent + "Call WN_CameraControl(\"" + op + "\", " + val + ", " + dur + ")")
			"trigger":
				var gid   := str(nd.get("group_id", 1))
				var delay := str(nd.get("delay",    0.0))
				_w(indent + "Call WN_Trigger(" + gid + ", " + delay + ")")
			# ── New trigger-style action nodes ─────────────────────────────
			"move":
				var prm := nd.get("params", {})
				var gid := _resolve_param(nd, prm, "Group_ID", "1")
				var mx  := _resolve_param(nd, prm, "X",        "0")
				var my  := _resolve_param(nd, prm, "Y",        "0")
				var dur := _resolve_param(nd, prm, "Duration", "0.5")
				_w(indent + "Call WN_Move(" + gid + ", " + mx + ", " + my + ", " + dur + ")")
			"rotate":
				var prm := nd.get("params", {})
				var gid := _resolve_param(nd, prm, "Group_ID", "1")
				var deg := _resolve_param(nd, prm, "Degrees",  "90")
				var dur := _resolve_param(nd, prm, "Duration", "0.5")
				_w(indent + "Call WN_Rotate(" + gid + ", " + deg + ", " + dur + ")")
			"scale":
				var prm := nd.get("params", {})
				var gid := _resolve_param(nd, prm, "Group_ID", "1")
				var sx  := _resolve_param(nd, prm, "Scale_X",  "1")
				var sy  := _resolve_param(nd, prm, "Scale_Y",  "1")
				var dur := _resolve_param(nd, prm, "Duration", "0.5")
				_w(indent + "Call WN_Scale(" + gid + ", " + sx + ", " + sy + ", " + dur + ")")
			"alpha":
				var prm := nd.get("params", {})
				var gid := _resolve_param(nd, prm, "Group_ID", "1")
				var opa := _resolve_param(nd, prm, "Alpha",    "1.0")
				var dur := _resolve_param(nd, prm, "Duration", "0.5")
				_w(indent + "Call WN_Alpha(" + gid + ", " + opa + ", " + dur + ")")
			"color trigger":
				var prm := nd.get("params", {})
				var ch  := _resolve_param(nd, prm, "Channel",  "1")
				var r   := _resolve_param(nd, prm, "R",        "255")
				var g   := _resolve_param(nd, prm, "G",        "255")
				var b   := _resolve_param(nd, prm, "B",        "255")
				var dur := _resolve_param(nd, prm, "Duration", "0.5")
				_w(indent + "Call WN_ColorTrigger(" + ch + ", " + r + ", " + g + ", " + b + ", " + dur + ")")
			"pulse":
				var prm := nd.get("params", {})
				var gid := _resolve_param(nd, prm, "Group_ID", "1")
				var r   := _resolve_param(nd, prm, "R",        "255")
				var g   := _resolve_param(nd, prm, "G",        "100")
				var b   := _resolve_param(nd, prm, "B",        "100")
				var fi  := _resolve_param(nd, prm, "Fade_In",  "0.2")
				var hld := _resolve_param(nd, prm, "Hold",     "0.5")
				var fo  := _resolve_param(nd, prm, "Fade_Out", "0.2")
				_w(indent + "Call WN_Pulse(" + gid + ", " + r + ", " + g + ", " + b + ", " + fi + ", " + hld + ", " + fo + ")")
			"spawn":
				var prm   := nd.get("params", {})
				var gid   := _resolve_param(nd, prm, "Group_ID", "1")
				var delay := _resolve_param(nd, prm, "Delay",    "0")
				_w(indent + "Call WN_Spawn(" + gid + ", " + delay + ")")
			"stop":
				var prm := nd.get("params", {})
				var gid := _resolve_param(nd, prm, "Group_ID", "1")
				_w(indent + "Call WN_Stop(" + gid + ")")
			"toggle":
				var prm := nd.get("params", {})
				var gid := _resolve_param(nd, prm, "Group_ID", "1")
				var act := _resolve_param(nd, prm, "Active",   "1")
				_w(indent + "Call WN_Toggle(" + gid + ", " + act + ")")
			"follow":
				var prm := nd.get("params", {})
				var gid := _resolve_param(nd, prm, "Group_ID",     "1")
				var tgt := _resolve_param(nd, prm, "Target_Group", "2")
				var xm  := _resolve_param(nd, prm, "X_Mod",        "1")
				var ym  := _resolve_param(nd, prm, "Y_Mod",        "1")
				var dur := _resolve_param(nd, prm, "Duration",     "1.0")
				_w(indent + "Call WN_Follow(" + gid + ", " + tgt + ", " + xm + ", " + ym + ", " + dur + ")")
			"shake":
				var prm  := nd.get("params", {})
				var str_ := _resolve_param(nd, prm, "Strength", "1")
				var intv := _resolve_param(nd, prm, "Interval", "0.1")
				var dur  := _resolve_param(nd, prm, "Duration", "0.5")
				_w(indent + "Call WN_Shake(" + str_ + ", " + intv + ", " + dur + ")")
			"play sfx":
				var prm := nd.get("params", {})
				var snd := _resolve_param(nd, prm, "Sound",  "")
				var vol := _resolve_param(nd, prm, "Volume", "1")
				var pit := _resolve_param(nd, prm, "Pitch",  "1")
				_w(indent + "Call WN_PlaySFX(\"" + snd + "\", " + vol + ", " + pit + ")")
			"animate":
				var prm := nd.get("params", {})
				var gid := _resolve_param(nd, prm, "Group_ID",  "1")
				var ani := _resolve_param(nd, prm, "Animation", "0")
				var spd := _resolve_param(nd, prm, "Speed",     "1")
				_w(indent + "Call WN_Animate(" + gid + ", " + ani + ", " + spd + ")")
			# ── New GD-equivalent nodes ───────────────────────────────────────────
			"counter":
				var prm   := nd.get("params", {})
				var cname := _resolve_param(nd, prm, "Name",  "score")
				var op    := _resolve_param(nd, prm, "Op",    "+=")
				var val   := _resolve_param(nd, prm, "Value", "1")
				match op:
					"+=": _w(indent + cname + " = " + cname + " + " + val)
					"-=": _w(indent + cname + " = " + cname + " - " + val)
					"*=": _w(indent + cname + " = " + cname + " * " + val)
					"/=": _w(indent + "If " + val + " <> 0 Then " + cname + " = " + cname + " / " + val)
					"%=": _w(indent + cname + " = " + cname + " Mod " + val)
					"=":  _w(indent + cname + " = " + val)
					_:    _w(indent + cname + " = " + cname + " + " + val + "  ' op=" + op)
			"random trig":
				var prm   := nd.get("params", {})
				var min_v := _resolve_param(nd, prm, "Min",      "0")
				var max_v := _resolve_param(nd, prm, "Max",      "100")
				var store := _resolve_param(nd, prm, "Store_To", "result")
				_w(indent + store + " = " + min_v + " + Rnd() * (" + max_v + " - " + min_v + ")")
			"branch":
				_emit_inline_branch(nd, indent)
			"cmp trig":
				_emit_inline_cmp_trig(nd, indent)
			"timer":
				var prm   := nd.get("params", {})
				var delay := _resolve_param(nd, prm, "Delay",  "1.0")
				var rep   := _resolve_param(nd, prm, "Repeat", "0")
				_w(indent + "Call WN_Timer(" + delay + ", " + rep + ")")
			"sequence":
				_emit_inline_sequence(nd, indent)
			"zoom":
				var prm := nd.get("params", {})
				var z   := _resolve_param(nd, prm, "Zoom",     "1.0")
				var dur := _resolve_param(nd, prm, "Duration", "0.5")
				_w(indent + "Call WN_Zoom(" + z + ", " + dur + ")")
			"camera move":
				var prm := nd.get("params", {})
				var tgt := _resolve_param(nd, prm, "Target_Group", "1")
				var dur := _resolve_param(nd, prm, "Duration",     "1.0")
				var ox  := _resolve_param(nd, prm, "X_Offset",     "0")
				var oy  := _resolve_param(nd, prm, "Y_Offset",     "0")
				_w(indent + "Call WN_CameraMove(" + tgt + ", " + dur + ", " + ox + ", " + oy + ")")
			"get prop":
				var prm   := nd.get("params", {})
				var path  := _resolve_param(nd, prm, "Node_Path", "Player")
				var prop  := _resolve_param(nd, prm, "Property",  "position.x")
				var store := _resolve_param(nd, prm, "Store_To",  "result")
				_w(indent + store + " = GetNode(\"" + path + "\")." + prop)
			"set prop":
				var prm  := nd.get("params", {})
				var path := _resolve_param(nd, prm, "Node_Path", "Player")
				var prop := _resolve_param(nd, prm, "Property",  "position.x")
				var val  := _resolve_param(nd, prm, "Value",     "0")
				_w(indent + "GetNode(\"" + path + "\")." + prop + " = " + val)
			"input poll":
				_emit_inline_input_poll(nd, indent)
			"expr":
				var prm   := nd.get("params", {})
				var store := _resolve_param(nd, prm, "Store_To",   "result")
				var xpr   := _resolve_param(nd, prm, "Expression", "0")
				_w(indent + store + " = " + xpr)
			"delta var":
				_emit_inline_delta_var(nd, indent)
			_:
				# Generic fallback
				var safe := working_nodes_codegen.sanitize_name(str(nd.get("title", n_name)), "WNAction")
				_w(indent + "Call " + safe + "()  ' kind=" + kind)

	# ─── Action sub (implementation body) ────────────────────────────────────

	## Look up a WN-palette intent hint from a free-form title.
	## Returns a 3-element array: [intent_key, runtime_call_line, comment].
	## intent_key is one of: "spawn","stop","toggle","move","rotate","scale",
	## "alpha","play_sfx","animate","shake","pulse","camera_move","zoom",
	## "set_prop","emit","wait","print","".  Empty key means "no hint found".
	static func _intent_from_title(title: String) -> Array:
		var t := title.to_lower()
		# Keyword → (intent, suggested runtime call, comment)
		var rules := [
			["shoot",   "spawn",     "Call WN_Spawn(1, 0)  ' fire a bullet from group 1"],
			["fire",    "spawn",     "Call WN_Spawn(1, 0)  ' fire a bullet from group 1"],
			["spawn",   "spawn",     "Call WN_Spawn(1, 0)  ' spawn a member of group 1"],
			["explode", "spawn",     "Call WN_Spawn(1, 0)  ' spawn explosion FX"],
			["die",     "stop",      "Call WN_Stop(1)  ' stop / despawn group 1"],
			["kill",    "stop",      "Call WN_Stop(1)  ' stop / despawn group 1"],
			["hide",    "toggle",    "Call WN_Toggle(1, 0)  ' hide group 1"],
			["show",    "toggle",    "Call WN_Toggle(1, 1)  ' show group 1"],
			["jump",    "set_prop",  "GetNode(\"Player\").velocity.y = -400  ' jump impulse"],
			["dash",    "move",      "Call WN_Move(1, 200, 0, 0.1)  ' short dash"],
			["fly",     "move",      "Call WN_Move(1, 0, -100, 1.0)  ' upward motion"],
			["walk",    "move",      "Call WN_Move(1, 40, 0, 1.0)  ' walk right"],
			["run",     "move",      "Call WN_Move(1, 80, 0, 1.0)  ' run right"],
			["move",    "move",      "Call WN_Move(1, 100, 0, 0.5)"],
			["push",    "move",      "Call WN_Move(1, 50, 0, 0.3)"],
			["spin",    "rotate",    "Call WN_Rotate(1, 360, 1.0)"],
			["rotat",   "rotate",    "Call WN_Rotate(1, 90, 0.5)"],
			["turn",    "rotate",    "Call WN_Rotate(1, 90, 0.5)"],
			["grow",    "scale",     "Call WN_Scale(1, 2, 2, 0.3)"],
			["shrink",  "scale",     "Call WN_Scale(1, 0.5, 0.5, 0.3)"],
			["scale",   "scale",     "Call WN_Scale(1, 1.5, 1.5, 0.3)"],
			["fade",    "alpha",     "Call WN_Alpha(1, 0.0, 0.5)"],
			["dim",     "alpha",     "Call WN_Alpha(1, 0.3, 0.5)"],
			["alpha",   "alpha",     "Call WN_Alpha(1, 1.0, 0.5)"],
			["pulse",   "pulse",     "Call WN_Pulse(1, 255, 100, 100, 0.2, 0.5, 0.2)"],
			["flash",   "pulse",     "Call WN_Pulse(1, 255, 255, 255, 0.05, 0.05, 0.1)"],
			["shake",   "shake",     "Call WN_Shake(1, 0.1, 0.5)"],
			["rumble",  "shake",     "Call WN_Shake(2, 0.05, 1.0)"],
			["zoom",    "zoom",      "Call WN_Zoom(1.5, 0.5)"],
			["pan",     "camera_move","Call WN_CameraMove(1, 1.0, 0, 0)"],
			["follow",  "set_prop",  "Call WN_Follow(1, 2, 1, 1, 1.0)"],
			["beep",    "play_sfx",  "Call WN_PlaySFX(\"\", 1, 1)  ' fill in sound path"],
			["ding",    "play_sfx",  "Call WN_PlaySFX(\"\", 1, 1)  ' fill in sound path"],
			["sound",   "play_sfx",  "Call WN_PlaySFX(\"\", 1, 1)  ' fill in sound path"],
			["sfx",     "play_sfx",  "Call WN_PlaySFX(\"\", 1, 1)  ' fill in sound path"],
			["play",    "play_sfx",  "Call WN_PlaySFX(\"\", 1, 1)  ' fill in sound path"],
			["music",   "play_sfx",  "Call WN_PlaySFX(\"\", 1, 1)  ' fill in music path"],
			["anim",    "animate",   "Call WN_Animate(1, 0, 1)"],
			["dance",   "animate",   "Call WN_Animate(1, 0, 1)  ' dance animation"],
			["set",     "set_prop",  "GetNode(\"Player\").position.x = 0  ' adjust property"],
			["assign",  "set_prop",  "GetNode(\"Player\").position.x = 0  ' adjust property"],
			["emit",    "emit",      "RaiseEvent OnAction"],
			["signal",  "emit",      "RaiseEvent OnAction"],
			["wait",    "wait",      "Call WN_Wait(0.5)"],
			["delay",   "wait",      "Call WN_Wait(0.5)"],
			["print",   "print",     "Print \"...\""],
			["log",     "print",     "Print \"...\""],
			["debug",   "print",     "Print \"DEBUG: \""],
		]
		for r in rules:
			if str(r[0]) in t:
				return [str(r[1]), str(r[2]), ""]
		return ["", "", ""]

	func _emit_action_sub(nd: Dictionary) -> void:
		var kind   := str(nd.get("_kind", "")).to_lower()
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))

		match kind:
			"action":
				# Prefer explicit action_type, fall back to scanning the title.
				var act_type := str(nd.get("action_type", "")).to_lower()
				var hint := _intent_from_title(title if act_type.is_empty() else act_type)
				_w("Sub Action_" + n_name + "()  ' " + title)
				if hint[0] != "":
					_w("    ' Inferred from title \"" + title + "\" → " + str(hint[0]))
					_w("    " + str(hint[1]))
				else:
					# Last-resort: keep the original substring-based fallbacks so we never
					# regress, but always end with a Print.
					if "move" in act_type:
						_w("    ' Move target node (no group context)")
					elif "rotat" in act_type:
						_w("    ' Rotate target node")
					elif "scale" in act_type:
						_w("    ' Scale target node")
					elif "anim" in act_type or "play" in act_type:
						_w("    ' Play animation or sound")
					elif "tween" in act_type:
						_w("    ' Tween target node property")
					elif "wait" in act_type:
						_w("    ' Wait / yield")
					elif "set" in act_type:
						_w("    ' Set property on target")
					elif "emit" in act_type:
						_w("    ' Emit a signal")
					elif "call" in act_type:
						_w("    ' Call method on target")
					_w("    Print \"Action_" + n_name + ": " + title + "\"")
				_w("End Sub")
				_w("")

			"movegroup":
				# Handled inline — no separate sub needed
				pass

			"trigger":
				# Handled inline — no separate sub needed
				pass

			_:
				# Handled inline — no separate sub needed
				pass

	# ─── Condition sub ────────────────────────────────────────────────────────

	func _emit_condition_sub(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var kind   := str(nd.get("_kind", "")).to_lower()

		if kind == "switch":
			_w("Function WN_Switch_" + n_name + "(ByVal condition As Boolean, ByVal true_val As Variant, ByVal false_val As Variant) As Variant")
			_w("    If condition Then")
			_w("        WN_Switch_" + n_name + " = true_val")
			_w("    Else")
			_w("        WN_Switch_" + n_name + " = false_val")
			_w("    End If")
			_w("End Function  ' Switch: " + title)
			_w("")
		else:
			var cmp_op  := str(nd.get("compare_op", "=="))
			var cmp_val := str(nd.get("compare_value", "0"))
			_w("Function WN_Cond_" + n_name + "(ByVal value As Variant) As Boolean")
			_w("    WN_Cond_" + n_name + " = (value " + cmp_op + " " + cmp_val + ")")
			_w("End Function  ' Condition: " + title)
			_w("")

	# ─── Loop sub ────────────────────────────────────────────────────────────

	func _emit_loop_sub(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var count  := int(nd.get("loop_count", 3))
		_w("Sub WN_Loop_" + n_name + "()")
		_w("    ' Loop: " + title)
		_w("    Dim i As Long")
		_w("    For i = 0 To " + str(count - 1) + " Step 1")
		_w("        ' TODO: body")
		_w("    Next i")
		_w("End Sub")
		_w("")

	# ─── Function node ────────────────────────────────────────────────────────

	func _emit_function_node(nd: Dictionary) -> void:
		var fn_name := working_nodes_codegen.sanitize_name(
			str(nd.get("fn_name", nd.get("title", "my_function"))), "WNFunction"
		)
		var ret_type := _map_type(str(nd.get("return_type", "void")))
		var title := str(nd.get("title", fn_name))

		if ret_type == "Variant" or str(nd.get("return_type", "void")).to_lower() == "void":
			_w("Sub " + fn_name + "(ByVal param_a As Double, ByVal param_b As Double)")
			_w("    ' Function node: " + title)
			_w("    ' TODO: implement body")
			_w("End Sub")
		else:
			_w("Function " + fn_name + "(ByVal param_a As Double, ByVal param_b As Double) As " + ret_type)
			_w("    ' Function node: " + title)
			_w("    " + fn_name + " = param_a  ' TODO: implement")
			_w("End Function")
		_w("")

	# ─── Math functions ───────────────────────────────────────────────────────

	func _emit_math_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var op     := str(nd.get("math_op", nd.get("title", "Add"))).to_lower()
		_w("Function WN_Math_" + n_name + "(ByVal a As Double, ByVal b As Double) As Double")
		_w("    ' Math node: " + title)
		match op:
			"add":            _w("    WN_Math_" + n_name + " = a + b")
			"subtract":       _w("    WN_Math_" + n_name + " = a - b")
			"multiply":       _w("    WN_Math_" + n_name + " = a * b")
			"divide":         _w("    If b <> 0 Then WN_Math_" + n_name + " = a / b Else WN_Math_" + n_name + " = 0")
			"multiply add":   _w("    WN_Math_" + n_name + " = a * b + 0  ' MultiplyAdd (c not wired)")
			"power":          _w("    WN_Math_" + n_name + " = a ^ b")
			"log":            _w("    WN_Math_" + n_name + " = Log(a)")
			"sqrt":           _w("    WN_Math_" + n_name + " = Sqr(a)")
			"absolute":       _w("    WN_Math_" + n_name + " = Abs(a)")
			"min":            _w("    If a < b Then WN_Math_" + n_name + " = a Else WN_Math_" + n_name + " = b")
			"max":            _w("    If a > b Then WN_Math_" + n_name + " = a Else WN_Math_" + n_name + " = b")
			"floor":          _w("    WN_Math_" + n_name + " = Int(a)")
			"ceil":           _w("    If a = Int(a) Then WN_Math_" + n_name + " = a Else WN_Math_" + n_name + " = Int(a) + 1")
			"round":          _w("    WN_Math_" + n_name + " = CLng(a)")
			"modulo":         _w("    WN_Math_" + n_name + " = a Mod b")
			"sin":            _w("    WN_Math_" + n_name + " = Sin(a)")
			"cos":            _w("    WN_Math_" + n_name + " = Cos(a)")
			"tan":            _w("    WN_Math_" + n_name + " = Tan(a)")
			"arctan":         _w("    WN_Math_" + n_name + " = Atn(a)")
			"arctan2":        _w("    WN_Math_" + n_name + " = Atn(a / b)")
			"lerp":           _w("    WN_Math_" + n_name + " = a + (b - a) * 0.5  ' t not wired")
			"clamp":          _w("    If a < 0 Then WN_Math_" + n_name + " = 0 ElseIf a > 1 Then WN_Math_" + n_name + " = 1 Else WN_Math_" + n_name + " = a")
			_:                _w("    WN_Math_" + n_name + " = a + b  ' op=" + op)
		_w("End Function")
		_w("")

	func _emit_boolmath_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var op     := str(nd.get("bool_op", "AND")).to_upper()
		_w("Function WN_BoolMath_" + n_name + "(ByVal a As Boolean, ByVal b As Boolean) As Boolean")
		_w("    ' BoolMath node: " + title)
		match op:
			"AND":  _w("    WN_BoolMath_" + n_name + " = a And b")
			"OR":   _w("    WN_BoolMath_" + n_name + " = a Or b")
			"NOT":  _w("    WN_BoolMath_" + n_name + " = Not a")
			"NAND": _w("    WN_BoolMath_" + n_name + " = Not (a And b)")
			"NOR":  _w("    WN_BoolMath_" + n_name + " = Not (a Or b)")
			"XOR":  _w("    WN_BoolMath_" + n_name + " = a Xor b")
			"XNOR": _w("    WN_BoolMath_" + n_name + " = Not (a Xor b)")
			_:      _w("    WN_BoolMath_" + n_name + " = a And b")
		_w("End Function")
		_w("")

	func _emit_vectormath_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		_w("' VectorMath node: " + title)
		_w("' (Vector operations use x/y/z components — expand as needed)")
		_w("Function WN_VecMath_" + n_name + "_X(ByVal ax As Double, ByVal ay As Double, ByVal bx As Double, ByVal by As Double) As Double")
		_w("    WN_VecMath_" + n_name + "_X = ax + bx  ' TODO: set correct vector op")
		_w("End Function")
		_w("Function WN_VecMath_" + n_name + "_Y(ByVal ax As Double, ByVal ay As Double, ByVal bx As Double, ByVal by As Double) As Double")
		_w("    WN_VecMath_" + n_name + "_Y = ay + by")
		_w("End Function")
		_w("")

	func _emit_maprange_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		_w("Function WN_MapRange_" + n_name + "(ByVal value As Double, ByVal from_min As Double, ByVal from_max As Double, ByVal to_min As Double, ByVal to_max As Double) As Double")
		_w("    ' MapRange node: " + title)
		_w("    If from_max = from_min Then")
		_w("        WN_MapRange_" + n_name + " = to_min")
		_w("    Else")
		_w("        WN_MapRange_" + n_name + " = to_min + (value - from_min) / (from_max - from_min) * (to_max - to_min)")
		_w("    End If")
		_w("End Function")
		_w("")

	func _emit_randomvalue_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		_w("Function WN_Random_" + n_name + "(ByVal min_val As Double, ByVal max_val As Double) As Double")
		_w("    ' RandomValue node: " + title)
		_w("    WN_Random_" + n_name + " = min_val + Rnd() * (max_val - min_val)")
		_w("End Function")
		_w("")

	func _emit_compare_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var op     := str(nd.get("compare_op", "< Less Than")).to_lower()
		_w("Function WN_Compare_" + n_name + "(ByVal a As Double, ByVal b As Double) As Boolean")
		_w("    ' Compare node: " + title)
		if "less than" in op or op == "<":
			_w("    WN_Compare_" + n_name + " = (a < b)")
		elif "greater than" in op or op == ">":
			_w("    WN_Compare_" + n_name + " = (a > b)")
		elif "lte" in op or op == "<=":
			_w("    WN_Compare_" + n_name + " = (a <= b)")
		elif "gte" in op or op == ">=":
			_w("    WN_Compare_" + n_name + " = (a >= b)")
		elif "not" in op or op == "!=":
			_w("    WN_Compare_" + n_name + " = (a <> b)")
		else:
			_w("    WN_Compare_" + n_name + " = (a = b)")
		_w("End Function")
		_w("")


# ─── Scene Generator ─────────────────────────────────────────────────────────

class _SceneGen:

	func build_2d(data: Dictionary, vg_script_path: String, root_type: String = "Node2D") -> String:
		return _build_scene(data, vg_script_path, false, root_type)

	func build_3d(data: Dictionary, vg_script_path: String, root_type: String = "Node3D") -> String:
		return _build_scene(data, vg_script_path, true, root_type)

	func _build_scene(data: Dictionary, vg_script_path: String, is_3d: bool, override_root: String = "") -> String:
		var root_type  := override_root if not override_root.is_empty() else ("Node3D" if is_3d else "Node2D")
		var child_type := "Node3D" if is_3d else "Node2D"

		var lines: PackedStringArray = PackedStringArray()
		var w := func(s: String): lines.append(s)

		# ── Collect groups and action nodes ───────────────────────────────
		# These are the graph's *logical* groups (Geometry-Dash-style group IDs).
		# They become:
		#   • One container Node2D/Node3D per group (sorts the scene tree)
		#   • A Godot scene group tag "wn_group_<id>" on every action object,
		#     so wn_runtime.vg can resolve them via get_nodes_in_group(…).
		var groups: Dictionary = {}
		for g in data.get("groups", []):
			groups[int(g.get("id", 0))] = g

		var nodes_list: Array = data.get("nodes", [])
		var action_kinds := [
			"action", "trigger", "movegroup", "rotategroup", "followtarget",
			"spawntrigger", "alphafade", "togglegroup", "pulseeffect",
			"cameracontrol", "colorchannel",
			# New trigger-style:
			"move", "rotate", "scale", "alpha", "color trigger",
			"pulse", "spawn", "stop", "toggle", "follow",
			"shake", "play sfx", "animate",
		]

		# ── load_steps + shared placeholder resources ─────────────────────
		# We emit a single shared mesh (3D) / the built-in ColorRect (2D) so
		# every spawned object is visible on first frame without needing the
		# user to wire up textures or meshes.
		var load_steps := 2  # script + shared resource
		w.call("[gd_scene load_steps=%d format=3 uid=\"uid://wn_generated\"]" % load_steps)
		w.call("")
		if not vg_script_path.is_empty():
			w.call("[ext_resource type=\"Script\" path=\"" + vg_script_path + "\" id=\"1_script\"]")
			w.call("")
		if is_3d:
			# Shared BoxMesh so every MeshInstance3D is visible. Size is
			# intentionally small — scale up via WN_Scale or edit-after-build.
			w.call("[sub_resource type=\"BoxMesh\" id=\"WNBox\"]")
			w.call("size = Vector3(1, 1, 1)")
			w.call("")

		# ── Root node ─────────────────────────────────────────────────────
		var scene_name := "WNScene"
		w.call("[node name=\"" + scene_name + "\" type=\"" + root_type + "\"]")
		if not vg_script_path.is_empty():
			w.call("script = ExtResource(\"1_script\")")
		w.call("")

		# Camera — guarantees anything visible actually renders. 2D: a
		# Camera2D centred on origin. 3D: a Camera3D pulled back along +Z.
		if is_3d:
			w.call("[node name=\"Camera3D\" type=\"Camera3D\" parent=\".\"]")
			w.call("transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 10)")
			w.call("current = true")
			w.call("")
			w.call("[node name=\"DirectionalLight3D\" type=\"DirectionalLight3D\" parent=\".\"]")
			w.call("transform = Transform3D(0.7071, -0.5, 0.5, 0, 0.7071, 0.7071, -0.7071, -0.5, 0.5, 0, 5, 0)")
			w.call("")
		else:
			w.call("[node name=\"Camera2D\" type=\"Camera2D\" parent=\".\"]")
			w.call("position = Vector2(0, 0)")
			w.call("")

		# ── Group containers ──────────────────────────────────────────────
		var emitted_groups: Dictionary = {}
		for nd in nodes_list:
			var n_kind := str(nd.get("kind", nd.get("type", "action"))).to_lower()
			if n_kind in action_kinds:
				var gid := int(nd.get("group", nd.get("wn_group", 1)))
				if gid > 0 and not emitted_groups.has(gid):
					emitted_groups[gid] = true
					var g_info: Dictionary = groups.get(gid, {})
					var g_name := working_nodes_codegen.sanitize_name(
						str(g_info.get("name", "Group%d" % gid)), "Group%d" % gid
					)
					w.call("[node name=\"" + g_name + "\" type=\"" + child_type + "\" parent=\".\"]")
					w.call("")

		# ── Per-node scene objects ────────────────────────────────────────
		for nd in nodes_list:
			var n_kind := str(nd.get("kind", nd.get("type", "action"))).to_lower()
			if not (n_kind in action_kinds):
				continue

			var n_name  := str(nd.get("name", nd.get("title", "WN_0")))
			var title   := str(nd.get("title", n_name))
			var obj_name := working_nodes_codegen.sanitize_name(title, "WNObj")
			var gid      := int(nd.get("group", nd.get("wn_group", 1)))
			var g_info: Dictionary = groups.get(gid, {})
			var g_parent := working_nodes_codegen.sanitize_name(
				str(g_info.get("name", "Group%d" % gid)), "Group%d" % gid
			)
			var parent_path := g_parent if emitted_groups.has(gid) else "."

			# Choose a visible node type per action kind.
			# 2D: ColorRect — instantly visible, no texture needed, the hex
			#     colour comes from the node's editor swatch if set.
			# 3D: MeshInstance3D with the shared WNBox SubResource.
			var obj_type := "MeshInstance3D" if is_3d else "ColorRect"

			# In Godot's .tscn format, scene-baked groups MUST live inside
			# the [node ...] header, not as a property below — otherwise
			# is_in_group() / get_nodes_in_group() won't see them.
			var groups_attr := " groups=[\"wn_group_%d\", \"wn_all\"]" % gid
			w.call("[node name=\"" + obj_name + "\" type=\"" + obj_type + "\" parent=\"" + parent_path + "\"" + groups_attr + "]")

			# Position from the graph node's canvas coordinates (scaled down
			# so a 1200×800 graph maps to a reasonable scene extent).
			var pos_arr: Array = nd.get("position", [0, 0])
			var px: float = float(pos_arr[0] if pos_arr.size() > 0 else 0) * 0.25
			var py: float = float(pos_arr[1] if pos_arr.size() > 1 else 0) * 0.25

			if is_3d:
				w.call("transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, " + "%.3f" % (px * 0.02) + ", " + "%.3f" % (-py * 0.02) + ", 0)")
				w.call("mesh = SubResource(\"WNBox\")")
			else:
				# ColorRect uses position + size, not just position.
				w.call("offset_left = " + "%.1f" % px)
				w.call("offset_top = " + "%.1f" % py)
				w.call("offset_right = " + "%.1f" % (px + 32.0))
				w.call("offset_bottom = " + "%.1f" % (py + 32.0))
				# Colour from the graph swatch (falls back to a visible default).
				var color_hex := str(nd.get("node_color", nd.get("color", "4a90e0")))
				if color_hex.begins_with("#"):
					color_hex = color_hex.substr(1)
				var cr := _hex_pair_to_float(color_hex, 0)
				var cg := _hex_pair_to_float(color_hex, 2)
				var cb := _hex_pair_to_float(color_hex, 4)
				w.call("color = Color(%.3f, %.3f, %.3f, 1)" % [cr, cg, cb])

			# Tag the kind in metadata so runtime introspection (e.g. the
			# debug overlay) can identify what each object was generated
			# from. The actual scene group tag was set in the [node] header
			# above — Godot ignores `groups = [...]` in property position.
			w.call("metadata/_wn_kind = \"" + n_kind + "\"")
			w.call("")

		return "\n".join(Array(lines))

	# Parse two hex chars at offset as a 0.0..1.0 float. Returns 0.5 on error.
	func _hex_pair_to_float(hex: String, offset: int) -> float:
		if offset + 1 >= hex.length():
			return 0.5
		var s := hex.substr(offset, 2)
		var v := s.hex_to_int()
		return float(v) / 255.0


# ─── GDScript Generator ───────────────────────────────────────────────────────

class _GDScriptGen:
	var _nodes: Dictionary = {}
	var _conns: Array = []
	var _lines: PackedStringArray = PackedStringArray()

	func build(data: Dictionary) -> String:
		_nodes = {}
		_conns = data.get("connections", [])
		_lines = PackedStringArray()
		for nd in data.get("nodes", []):
			var n_name: String = str(nd.get("name", nd.get("title", "WN_0")))
			var n_kind: String = str(nd.get("kind", nd.get("type", "action"))).capitalize()
			var entry: Dictionary = nd.duplicate()
			entry["_kind"] = n_kind
			entry["_name"] = n_name
			_nodes[n_name] = entry

		_w("# Generated by Working Nodes — VisualGasic")
		_w("# Edit the graph in Working Nodes to regenerate, or edit here directly.")
		_w("# To run: attach this script to a Node in the scene.")
		_w("")
		_w("extends Node")
		_w("")

		# Variables
		var var_nodes := _nodes_of_kind("Variable")
		if not var_nodes.is_empty():
			_w("# --- Variables ---")
			for nd in var_nodes:
				var vname := working_nodes_codegen.sanitize_name(
					str(nd.get("var_name", nd.get("title", "my_var"))), "my_var")
				var vtype := _gd_type(str(nd.get("var_type", "float")))
				_w("var %s: %s" % [vname, vtype])
			_w("")

		# Event → func mappings
		var event_kinds := ["Event", "Timedevent", "Collisiontrigger"]
		var event_nodes: Array = []
		for k in event_kinds:
			event_nodes.append_array(_nodes_of_kind(k))

		if event_nodes.is_empty():
			_w("func _ready() -> void:")
			_w("\t# No Event nodes — all actions called here")
			for nd in _nodes_of_kind("Action"):
				var an := str(nd.get("_name", ""))
				_w("\t_%s()" % an.to_lower())
			if _nodes_of_kind("Action").is_empty():
				_w("\tpass")
		else:
			for nd in event_nodes:
				_emit_event_func(nd)

		# Per-action funcs
		for nd in _nodes_of_kind("Action"):
			_emit_action_func(nd)

		# Math funcs
		for nd in _nodes_of_kind("Math"):
			_emit_math_func(nd)
		for nd in _nodes_of_kind("Boolmath"):
			_emit_boolmath_func(nd)

		# Function nodes
		for nd in _nodes_of_kind("Function"):
			_emit_function_node(nd)

		return "\n".join(Array(_lines))

	func _w(line: String) -> void:
		_lines.append(line)

	func _nodes_of_kind(kind: String) -> Array:
		var out: Array = []
		var lk := kind.to_lower()
		for n in _nodes.values():
			if str(n.get("_kind", "")).to_lower() == lk:
				out.append(n)
		return out

	func _gd_type(t: String) -> String:
		match t.to_lower():
			"float", "double": return "float"
			"int", "integer", "long": return "int"
			"bool", "boolean": return "bool"
			"string": return "String"
			"vector2": return "Vector2"
			"vector3": return "Vector3"
			"color": return "Color"
			_: return "Variant"

	func _exec_chain(start_name: String) -> Array:
		var ordered: Array = []
		var visited: Dictionary = {}
		var queue: Array = [start_name]
		while not queue.is_empty():
			var cur: String = queue.pop_front()
			if visited.has(cur): continue
			visited[cur] = true
			if _nodes.has(cur): ordered.append(_nodes[cur])
			for c in _conns:
				if str(c.get("from", "")) == cur:
					queue.push_back(str(c.get("to", "")))
		return ordered

	func _event_func_name(ev_type: String, n_name: String) -> String:
		var t := ev_type.to_lower()
		if "start" in t or "ready" in t or "load" in t: return "_ready"
		elif "process" in t or "update" in t or "frame" in t: return "_process"
		elif "input" in t or "click" in t or "touch" in t: return "_input"
		elif "timer" in t: return "_on_timer_timeout"
		elif "collision" in t: return "_on_body_entered"
		else:
			return "_on_" + working_nodes_codegen.sanitize_name(ev_type, "event_" + n_name).to_lower()

	func _emit_event_func(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var ev_type := str(nd.get("event_type", nd.get("title", "On Ready")))
		var fn_name := _event_func_name(ev_type, n_name)
		var args := ""
		if fn_name == "_process": args = "delta: float"
		elif fn_name == "_input": args = "event: InputEvent"
		elif fn_name == "_on_body_entered": args = "body: Node"
		_w("")
		_w("func %s(%s) -> void:" % [fn_name, args])
		if nd.get("_breakpoint", false):
			_w("\tprint(\">>> BREAKPOINT: %s\")" % str(nd.get("title", n_name)))
		var chain := _exec_chain(n_name)
		var had_body := false
		for linked in chain:
			if str(linked.get("_name", "")) == n_name: continue
			var kind := str(linked.get("_kind", "")).to_lower()
			match kind:
				"action":
					_w("\t_%s()" % str(linked.get("_name", "")).to_lower())
					had_body = true
				"variable": pass
				_:
					_w("\tpass  # %s: %s" % [kind, str(linked.get("title", ""))])
					had_body = true
		if not had_body:
			_w("\tpass")

	func _emit_action_func(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var act    := str(nd.get("action_type", nd.get("title", "print"))).to_lower()
		_w("")
		_w("func _%s() -> void:  # %s" % [n_name.to_lower(), title])
		if nd.get("_breakpoint", false):
			_w("\tprint(\">>> BREAKPOINT: %s\")" % title)
		if "move" in act:          _w("\tposition.x += 10.0")
		elif "rotat" in act:       _w("\trotation_degrees += 10.0")
		elif "scale" in act:       _w("\tscale *= 1.1")
		elif "print" in act or "log" in act: _w("\tprint(\"%s\")" % title)
		elif "anim" in act:        _w("\t# $AnimationPlayer.play(\"animation_name\")")
		elif "tween" in act:
			_w("\tvar tween := create_tween()")
			_w("\ttween.tween_property(self, \"position\", Vector2.ZERO, 0.5)")
		elif "wait" in act:        _w("\tawait get_tree().create_timer(1.0).timeout")
		elif "emit" in act:        _w("\t# emit_signal(\"signal_name\")")
		elif "call" in act:        _w("\t# call(\"method_name\")")
		elif "set" in act:         _w("\t# set(\"property_name\", value)")
		else:                      _w("\tprint(\"%s executed\")" % title)

	func _emit_math_func(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var op     := str(nd.get("math_op", nd.get("title", "add"))).to_lower()
		_w("")
		_w("func _wn_math_%s(a: float, b: float) -> float:  # %s" % [n_name.to_lower(), title])
		match op:
			"add":        _w("\treturn a + b")
			"subtract":   _w("\treturn a - b")
			"multiply":   _w("\treturn a * b")
			"divide":     _w("\treturn a / b if b != 0.0 else 0.0")
			"power":      _w("\treturn pow(a, b)")
			"sqrt":       _w("\treturn sqrt(a)")
			"absolute":   _w("\treturn abs(a)")
			"min":        _w("\treturn minf(a, b)")
			"max":        _w("\treturn maxf(a, b)")
			"floor":      _w("\treturn floor(a)")
			"ceil":       _w("\treturn ceil(a)")
			"round":      _w("\treturn round(a)")
			"sin":        _w("\treturn sin(a)")
			"cos":        _w("\treturn cos(a)")
			"tan":        _w("\treturn tan(a)")
			"lerp":       _w("\treturn lerp(a, b, 0.5)  # t not wired")
			"clamp":      _w("\treturn clamp(a, 0.0, 1.0)")
			_:            _w("\treturn a + b  # op=%s" % op)

	func _emit_boolmath_func(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var op     := str(nd.get("bool_op", "AND")).to_upper()
		_w("")
		_w("func _wn_bool_%s(a: bool, b: bool) -> bool:  # %s" % [n_name.to_lower(), title])
		match op:
			"AND":  _w("\treturn a and b")
			"OR":   _w("\treturn a or b")
			"NOT":  _w("\treturn not a")
			"NAND": _w("\treturn not (a and b)")
			"NOR":  _w("\treturn not (a or b)")
			"XOR":  _w("\treturn a != b")
			"XNOR": _w("\treturn a == b")
			_:      _w("\treturn a and b")

	func _emit_function_node(nd: Dictionary) -> void:
		var fn_name := working_nodes_codegen.sanitize_name(
			str(nd.get("fn_name", nd.get("title", "my_function"))), "wn_function")
		var ret := str(nd.get("return_type", "void")).to_lower()
		var gd_ret := "void" if ret in ["void", ""] else _gd_type(ret)
		_w("")
		_w("func %s(param_a: float, param_b: float) -> %s:" % [fn_name, gd_ret])
		if gd_ret == "void":
			_w("\tpass  # TODO: implement")
		else:
			_w("\treturn param_a  # TODO: implement")


# ─── VG Parser (round-trip import) ───────────────────────────────────────────
# Parses the top-level Sub/Function/Dim statements in a .vg file and creates
# a minimal Working Nodes graph dictionary that the editor can load.

class _VGParser:

	# Map from WN_xxx runtime call → (kind, [param_key1, param_key2, ...]).
	# Mirrors the call signatures emitted by _emit_action_call().
	const _WN_CALL_TABLE := {
		"wn_move":         ["move",          ["Group_ID","X","Y","Duration"]],
		"wn_rotate":       ["rotate",        ["Group_ID","Degrees","Duration"]],
		"wn_scale":        ["scale",         ["Group_ID","Scale_X","Scale_Y","Duration"]],
		"wn_alpha":        ["alpha",         ["Group_ID","Alpha","Duration"]],
		"wn_pulse":        ["pulse",         ["Group_ID","R","G","B","Fade_In","Hold","Fade_Out"]],
		"wn_shake":        ["shake",         ["Strength","Interval","Duration"]],
		"wn_spawn":        ["spawn",         ["Group_ID","Delay"]],
		"wn_stop":         ["stop",          ["Group_ID"]],
		"wn_toggle":       ["toggle",        ["Group_ID","Active"]],
		"wn_follow":       ["follow",        ["Group_ID","Target_Group","X_Mod","Y_Mod","Duration"]],
		"wn_playsfx":      ["play sfx",      ["Sound","Volume","Pitch"]],
		"wn_play_sfx":     ["play sfx",      ["Sound","Volume","Pitch"]],
		"wn_animate":      ["animate",       ["Group_ID","Animation","Speed"]],
		"wn_zoom":         ["zoom",          ["Zoom","Duration"]],
		"wn_cameramove":   ["camera move",   ["Target_Group","Duration","X_Offset","Y_Offset"]],
		"wn_camera_move":  ["camera move",   ["Target_Group","Duration","X_Offset","Y_Offset"]],
		"wn_timer":        ["timer",         ["Delay","Repeat"]],
		"wn_colortrigger": ["color trigger", ["Channel","R","G","B","Duration"]],
		"wn_color_trigger":["color trigger", ["Channel","R","G","B","Duration"]],
	}

	func parse(vg_code: String) -> Dictionary:
		var lines := vg_code.split("\n")
		var nodes: Array = []
		var connections: Array = []
		var id_box: Array = [1]  # boxed so helpers can ++ it

		var event_entries: Array = []   # {title, event_type, body_lines}
		var action_entries: Array = []  # {title, body_lines}
		var fn_entries: Array = []      # {title, body_lines}

		# ── Pass 1: split into Sub / Function regions, capture bodies ────
		var cur_kind := ""   # "" | "sub" | "function"
		var cur_title := ""
		var cur_body: Array = []
		for raw_line in lines:
			var line := raw_line.strip_edges()
			if line.is_empty() or line.begins_with("'"):
				if cur_kind != "":
					cur_body.append(line)
				continue
			var tl := line.to_lower()

			# Variable declarations at top level only.
			if cur_kind == "" and tl.begins_with("dim "):
				var parts := line.split(" ", false)
				if parts.size() >= 4:
					nodes.append({
						"name": "WN_Var_%d" % id_box[0],
						"title": parts[1],
						"kind": "Variable", "type": "variable",
						"var_name": parts[1], "var_type": parts[3],
						"position": [60, 60 + id_box[0] * 90],
					})
					id_box[0] += 1
				continue

			# Sub start
			if tl.begins_with("sub "):
				cur_kind = "sub"
				cur_title = _extract_sub_name(line)
				cur_body = []
				continue
			# Function start
			if tl.begins_with("function "):
				cur_kind = "function"
				cur_title = _extract_sub_name(line)
				cur_body = []
				continue
			# End Sub / End Function
			if tl == "end sub" or tl == "end function":
				if cur_kind == "sub":
					var ev_type := _classify_event(cur_title)
					if ev_type != "":
						event_entries.append({"title": cur_title, "event_type": ev_type, "body": cur_body})
					else:
						action_entries.append({"title": cur_title, "body": cur_body})
				elif cur_kind == "function":
					fn_entries.append({"title": cur_title, "body": cur_body})
				cur_kind = ""
				cur_title = ""
				cur_body = []
				continue

			if cur_kind != "":
				cur_body.append(line)

		# ── Pass 2: emit Event nodes + parse their bodies into child nodes
		var x := 120
		var first_event_name := ""
		for i in event_entries.size():
			var e: Dictionary = event_entries[i]
			var en := "WN_Ev_%d" % id_box[0]
			nodes.append({
				"name": en, "title": str(e.title),
				"kind": "Event", "type": "event",
				"event_type": e.get("event_type", "On Start"),
				"position": [x + i * 340, 120],
			})
			id_box[0] += 1
			if first_event_name.is_empty():
				first_event_name = en
			_parse_body_into_nodes(e.get("body", []), en, x + i * 340, 220, nodes, connections, id_box)

		# Emit action subs as Action nodes (chain to first event for back-compat,
		# but don't bury their bodies — they get their own child chain too).
		var prev_name := first_event_name
		for i in action_entries.size():
			var a: Dictionary = action_entries[i]
			var an := "WN_Act_%d" % id_box[0]
			nodes.append({
				"name": an, "title": str(a.title),
				"kind": "Action", "type": "action",
				"position": [x + i * 240, 500],
			})
			id_box[0] += 1
			if not prev_name.is_empty():
				connections.append({"from": prev_name, "from_port": 0, "to": an, "to_port": 0})
				prev_name = an
			_parse_body_into_nodes(a.get("body", []), an, x + i * 240, 600, nodes, connections, id_box)

		# Function nodes (display only — bodies are still text for now)
		for i in fn_entries.size():
			var f: Dictionary = fn_entries[i]
			var fn := "WN_Fn_%d" % id_box[0]
			nodes.append({
				"name": fn, "title": str(f.title),
				"kind": "Function", "type": "function",
				"fn_name": str(f.title),
				"position": [x + i * 240, 800],
			})
			id_box[0] += 1

		if nodes.is_empty() and connections.is_empty():
			# Fallback: create a single Event + Action node
			nodes.append({"name":"WN_Ev_1","title":"Form_Load","kind":"Event","type":"event","event_type":"On Start","position":[120,120]})
			nodes.append({"name":"WN_Act_2","title":"Imported Action","kind":"Action","type":"action","position":[400,200]})
			connections.append({"from":"WN_Ev_1","from_port":0,"to":"WN_Act_2","to_port":0})

		return {
			"version": 1,
			"next_node_id": id_box[0],
			"next_group_id": 2,
			"nodes": nodes,
			"connections": connections,
			"groups": [{"id": 1, "name": "Group 1", "color": "#88AAFF"}],
		}

	## Parses a Sub body into a chain of child nodes hanging off parent_name.
	## Handles `Call WN_xxx(args)`, top-level `If X op Y Then ... Else ... End If`,
	## `GetNode("path").prop = value`, `var = GetNode("path").prop`, and
	## bare assignments. Falls back to a Print/comment node for unrecognised
	## statements so nothing is silently lost.
	func _parse_body_into_nodes(body: Array, parent_name: String, base_x: int, base_y: int,
								nodes: Array, connections: Array, id_box: Array) -> void:
		var prev := parent_name
		var y := base_y
		var i := 0
		while i < body.size():
			var raw: String = str(body[i])
			var s := raw.strip_edges()
			if s.is_empty() or s.begins_with("'"):
				i += 1
				continue
			var sl := s.to_lower()

			# Call WN_xxx(args...)
			if sl.begins_with("call wn_") or sl.begins_with("call  wn_"):
				var name_dict := _parse_wn_call(s, id_box, base_x, y)
				if not name_dict.is_empty():
					nodes.append(name_dict)
					connections.append({"from": prev, "from_port": 0,
						"to": name_dict["name"], "to_port": 0})
					prev = name_dict["name"]
					y += 90
					i += 1
					continue

			# If <expr> Then [ ... Else ... ] End If  (single-line or block)
			if sl.begins_with("if ") and " then" in sl:
				var consumed: Array = [0]
				var br := _parse_if_block(body, i, id_box, base_x, y, consumed)
				if not br.is_empty():
					nodes.append(br["node"])
					connections.append({"from": prev, "from_port": 0,
						"to": br["node"]["name"], "to_port": 0})
					# Wire branch true/false to any inline single-line tails
					for child in br.get("children", []):
						nodes.append(child["node"])
						connections.append({"from": br["node"]["name"],
							"from_port": int(child.get("port", 0)),
							"to": child["node"]["name"], "to_port": 0})
					prev = br["node"]["name"]
					y += 90
					i += consumed[0]
					continue

			# GetNode("path").prop = value  → set_prop node
			if sl.begins_with("getnode("):
				var sp := _parse_set_prop(s, id_box, base_x, y)
				if not sp.is_empty():
					nodes.append(sp)
					connections.append({"from": prev, "from_port": 0,
						"to": sp["name"], "to_port": 0})
					prev = sp["name"]
					y += 90
					i += 1
					continue

			# var = GetNode("path").prop  → get_prop node
			var eq_idx := s.find("=")
			if eq_idx > 0 and "getnode(" in sl.substr(eq_idx):
				var gp := _parse_get_prop(s, eq_idx, id_box, base_x, y)
				if not gp.is_empty():
					nodes.append(gp)
					connections.append({"from": prev, "from_port": 0,
						"to": gp["name"], "to_port": 0})
					prev = gp["name"]
					y += 90
					i += 1
					continue

			# Print "..." → Action node
			if sl.begins_with("print "):
				var pn := {
					"name": "WN_Print_%d" % id_box[0],
					"title": "Print", "kind": "Action", "type": "action",
					"action_type": "print",
					"position": [base_x, y],
					"params": {"Text": s.substr(6).strip_edges()},
				}
				id_box[0] += 1
				nodes.append(pn)
				connections.append({"from": prev, "from_port": 0, "to": pn["name"], "to_port": 0})
				prev = pn["name"]
				y += 90
				i += 1
				continue

			# Fallback: keep the raw line as an Action node with the source
			# preserved in params so the round-trip is lossless.
			var fb := {
				"name": "WN_Raw_%d" % id_box[0],
				"title": s if s.length() <= 32 else s.substr(0, 29) + "...",
				"kind": "Action", "type": "action",
				"action_type": "raw",
				"position": [base_x, y],
				"params": {"Source": s},
			}
			id_box[0] += 1
			nodes.append(fb)
			connections.append({"from": prev, "from_port": 0, "to": fb["name"], "to_port": 0})
			prev = fb["name"]
			y += 90
			i += 1

	## Parse a single `Call WN_xxx(a, b, c)` line into a node dict.
	## Returns {} when the call name isn't in the table.
	func _parse_wn_call(line: String, id_box: Array, x: int, y: int) -> Dictionary:
		# Strip leading "Call " (case-insensitive).
		var l := line.strip_edges()
		var lower := l.to_lower()
		if lower.begins_with("call "):
			l = l.substr(5).strip_edges()
		var lp := l.find("(")
		var rp := l.rfind(")")
		if lp < 0 or rp < lp:
			return {}
		var fn_name := l.substr(0, lp).strip_edges().to_lower()
		if not _WN_CALL_TABLE.has(fn_name):
			return {}
		var args_str := l.substr(lp + 1, rp - lp - 1)
		var args := _split_args(args_str)
		var entry: Array = _WN_CALL_TABLE[fn_name]
		var kind := str(entry[0])
		var keys: Array = entry[1]
		var params := {}
		for j in min(keys.size(), args.size()):
			params[str(keys[j])] = str(args[j]).strip_edges()
		var nd := {
			"name": "WN_%s_%d" % [kind.capitalize().replace(" ", ""), id_box[0]],
			"title": kind.capitalize(),
			"kind": kind.capitalize(), "type": kind.replace(" ", "_"),
			"position": [x, y], "params": params,
		}
		id_box[0] += 1
		return nd

	## Split a comma-arg list, respecting nested parens and double-quoted strings.
	func _split_args(s: String) -> Array:
		var out: Array = []
		var depth := 0
		var in_str := false
		var buf := ""
		for ch in s:
			if in_str:
				buf += ch
				if ch == "\"":
					in_str = false
				continue
			if ch == "\"":
				in_str = true
				buf += ch
				continue
			if ch == "(":
				depth += 1
				buf += ch
				continue
			if ch == ")":
				depth -= 1
				buf += ch
				continue
			if ch == "," and depth == 0:
				out.append(buf.strip_edges())
				buf = ""
				continue
			buf += ch
		if not buf.strip_edges().is_empty():
			out.append(buf.strip_edges())
		return out

	## Parse an `If <a> <op> <b> Then [...]` line (and surrounding multi-line
	## If/Else/End If if it is a block) into a Branch node + optional child tails.
	## Returns {} when the header is unparseable.
	func _parse_if_block(body: Array, start_i: int, id_box: Array, x: int, y: int,
						 consumed_out: Array) -> Dictionary:
		var first: String = str(body[start_i]).strip_edges()
		var first_l := first.to_lower()
		var then_idx := first_l.find(" then")
		if then_idx < 0:
			return {}
		var head := first.substr(3, then_idx - 3).strip_edges()  # everything between "If " and " Then"
		var op_info := _split_condition(head)
		if op_info.is_empty():
			return {}
		var tail := first.substr(then_idx + 5).strip_edges()  # text after "Then"

		var node := {
			"name": "WN_Branch_%d" % id_box[0],
			"title": "If %s %s %s" % [op_info[0], op_info[1], op_info[2]],
			"kind": "Cmp Trig", "type": "cmp_trig",
			"position": [x, y],
			"params": {"A": op_info[0], "Op": op_info[1], "B": op_info[2]},
		}
		id_box[0] += 1

		var children: Array = []

		# Single-line If: `If X = Y Then doSomething`  (no Else, no End If)
		if not tail.is_empty():
			consumed_out[0] = 1
			# Try parsing the tail as its own statement (WN call or Print).
			var child := _parse_single_statement_to_node(tail, id_box, x + 240, y)
			if not child.is_empty():
				children.append({"node": child, "port": 0})
			return {"node": node, "children": children}

		# Block form: scan for matching End If, capturing then/else bodies.
		var j := start_i + 1
		var depth := 1
		var in_else := false
		var then_body: Array = []
		var else_body: Array = []
		while j < body.size():
			var ln := str(body[j]).strip_edges()
			var lnl := ln.to_lower()
			if lnl.begins_with("if ") and " then" in lnl and not lnl.ends_with("then"):
				# inline if inside body — depth doesn't change, treat as raw
				pass
			elif lnl.begins_with("if ") and lnl.ends_with("then"):
				depth += 1
			elif lnl == "end if":
				depth -= 1
				if depth == 0:
					j += 1
					break
			elif lnl == "else" and depth == 1:
				in_else = true
				j += 1
				continue
			if in_else:
				else_body.append(ln)
			else:
				then_body.append(ln)
			j += 1
		consumed_out[0] = j - start_i

		# Take the first statement from each branch and wire as a child.
		for stmt in then_body:
			var c := _parse_single_statement_to_node(stmt, id_box, x + 240, y)
			if not c.is_empty():
				children.append({"node": c, "port": 0})
				break
		for stmt in else_body:
			var c2 := _parse_single_statement_to_node(stmt, id_box, x + 240, y + 90)
			if not c2.is_empty():
				children.append({"node": c2, "port": 1})
				break

		return {"node": node, "children": children}

	## Split "a OP b" using the longest matching VG operator.
	## Returns [a, op, b] or [] if no operator was found.
	func _split_condition(head: String) -> Array:
		var ops := ["<>", ">=", "<=", "==", "=", ">", "<"]
		for op in ops:
			var idx := head.find(op)
			if idx >= 0:
				var a := head.substr(0, idx).strip_edges()
				var b := head.substr(idx + op.length()).strip_edges()
				return [a, op, b]
		return []

	func _parse_single_statement_to_node(stmt: String, id_box: Array, x: int, y: int) -> Dictionary:
		var sl := stmt.to_lower().strip_edges()
		if sl.begins_with("call wn_"):
			return _parse_wn_call(stmt, id_box, x, y)
		if sl.begins_with("getnode("):
			return _parse_set_prop(stmt, id_box, x, y)
		if sl.begins_with("print "):
			var pn := {
				"name": "WN_Print_%d" % id_box[0],
				"title": "Print", "kind": "Action", "type": "action",
				"action_type": "print",
				"position": [x, y],
				"params": {"Text": stmt.substr(6).strip_edges()},
			}
			id_box[0] += 1
			return pn
		# Generic raw fallback
		var fb := {
			"name": "WN_Raw_%d" % id_box[0],
			"title": stmt if stmt.length() <= 32 else stmt.substr(0, 29) + "...",
			"kind": "Action", "type": "action",
			"action_type": "raw",
			"position": [x, y],
			"params": {"Source": stmt},
		}
		id_box[0] += 1
		return fb

	## Parse `GetNode("path").prop = value` → set_prop node.
	func _parse_set_prop(line: String, id_box: Array, x: int, y: int) -> Dictionary:
		var eq := line.find("=")
		if eq < 0:
			return {}
		var lhs := line.substr(0, eq).strip_edges()
		var rhs := line.substr(eq + 1).strip_edges()
		var lhs_l := lhs.to_lower()
		if not lhs_l.begins_with("getnode("):
			return {}
		# Extract path
		var q1 := lhs.find("\"")
		var q2 := lhs.find("\"", q1 + 1)
		if q1 < 0 or q2 < 0:
			return {}
		var path := lhs.substr(q1 + 1, q2 - q1 - 1)
		# Property is everything after the closing `).`
		var dot := lhs.find(").", q2)
		if dot < 0:
			return {}
		var prop := lhs.substr(dot + 2).strip_edges()
		var nd := {
			"name": "WN_SetProp_%d" % id_box[0],
			"title": "Set " + prop, "kind": "Set Prop", "type": "set_prop",
			"position": [x, y],
			"params": {"Node_Path": path, "Property": prop, "Value": rhs},
		}
		id_box[0] += 1
		return nd

	## Parse `var = GetNode("path").prop` → get_prop node.
	func _parse_get_prop(line: String, eq_idx: int, id_box: Array, x: int, y: int) -> Dictionary:
		var lhs := line.substr(0, eq_idx).strip_edges()
		var rhs := line.substr(eq_idx + 1).strip_edges()
		var q1 := rhs.find("\"")
		var q2 := rhs.find("\"", q1 + 1)
		if q1 < 0 or q2 < 0:
			return {}
		var path := rhs.substr(q1 + 1, q2 - q1 - 1)
		var dot := rhs.find(").", q2)
		if dot < 0:
			return {}
		var prop := rhs.substr(dot + 2).strip_edges()
		var nd := {
			"name": "WN_GetProp_%d" % id_box[0],
			"title": "Get " + prop, "kind": "Get Prop", "type": "get_prop",
			"position": [x, y],
			"params": {"Node_Path": path, "Property": prop, "Store_To": lhs},
		}
		id_box[0] += 1
		return nd

	func _extract_sub_name(line: String) -> String:
		var after_kw := line.split(" ", false)
		var raw := after_kw[1] if after_kw.size() > 1 else "Unknown"
		return raw.split("(")[0]

	func _classify_event(sub_name: String) -> String:
		var tl := sub_name.to_lower()
		if "form_load" in tl or "form_ready" in tl: return "On Start"
		elif "form_process" in tl or "_process" in tl: return "On Frame"
		elif "form_keydown" in tl or "keydown" in tl: return "On Input"
		elif "form_timer" in tl or "timer" in tl: return "On Timer"
		elif "form_click" in tl or "click" in tl: return "On Click"
		elif "form_signal" in tl or "signal" in tl: return "On Signal"
		elif "form_collision" in tl or "collision" in tl: return "On Collision"
		elif "form_" in tl: return "On Start"
		return ""  # Not an event sub
