extends SceneTree

# Auto-generated by tools/generate_coverage_tests.py
# Loads each generated .vg test and calls RunTest()

func _init():
	var test_files := [
		"res://tests/generated/test_arith_basic.vg",
		"res://tests/generated/test_arith_negate.vg",
		"res://tests/generated/test_arith_string_concat.vg",
		"res://tests/generated/test_arith_format_op.vg",
		"res://tests/generated/test_compare_ops.vg",
		"res://tests/generated/test_logic_ops.vg",
		"res://tests/generated/test_ctrl_if_elseif.vg",
		"res://tests/generated/test_ctrl_for_next.vg",
		"res://tests/generated/test_ctrl_while_wend.vg",
		"res://tests/generated/test_ctrl_do_loop.vg",
		"res://tests/generated/test_ctrl_select_case.vg",
		"res://tests/generated/test_ctrl_for_each.vg",
		"res://tests/generated/test_func_return.vg",
		"res://tests/generated/test_func_recursive.vg",
		"res://tests/generated/test_array_basic.vg",
		"res://tests/generated/test_array_set.vg",
		"res://tests/generated/test_dict_basic.vg",
		"res://tests/generated/test_type_vector2.vg",
		"res://tests/generated/test_type_vector3.vg",
		"res://tests/generated/test_type_color.vg",
		"res://tests/generated/test_obj_node_new.vg",
		"res://tests/generated/test_obj_refcounted_new.vg",
		"res://tests/generated/test_obj_material_new.vg",
		"res://tests/generated/test_enum_input.vg",
		"res://tests/generated/test_enum_key_constants.vg",
		"res://tests/generated/test_builtin_math.vg",
		"res://tests/generated/test_builtin_is_zero_approx.vg",
		"res://tests/generated/test_string_methods.vg",
		"res://tests/generated/test_string_pad_decimals.vg",
		"res://tests/generated/test_typeof_is.vg",
		"res://tests/generated/test_error_on_error.vg",
		"res://tests/generated/test_deep_chain.vg",
		"res://tests/generated/test_member_assign_new.vg",
		"res://tests/generated/test_dim_initializer.vg",
		"res://tests/generated/test_with_block.vg",
		"res://tests/generated/test_iif_expr.vg",
		"res://tests/generated/test_singleton_input.vg",
	]
	
	var passed := 0
	var failed := 0
	var errors := []
	
	for path in test_files:
		var script = load(path)
		if script == null:
			print("LOAD_FAIL:" + path)
			failed += 1
			errors.append(path + " (failed to load)")
			continue
		var instance = script.new()
		if instance.has_method("RunTest"):
			instance.RunTest()
		elif instance.has_method("_Ready"):
			instance._Ready()
		else:
			print("NO_ENTRY:" + path)
			failed += 1
	
	print("")
	print("=== Coverage Test Results ===")
	print("Total: " + str(test_files.size()))
	print("Done")
	quit()
