extends Node2D
## About Visual Gasic — backrooms segment after shaders (~42s, wait-for-input in portal).
##
## Oval border scroller + Pac-Man belt + benchmark terminal panel. Zero external art assets.
## Portal API matches shader_showcase_manager (set_showcase_frozen, reset_for_portal, …).
## Standalone: advances to squash_tease_main on timer; embedded: backrooms controls duration/input.

const SW := 1280.0
const SH := 720.0
const CX := 640.0
const CY := 360.0
const NEXT_SCENE := "res://squash_tease_main.tscn"

const BORDER_INSET := 56.0
const PACMAN_SPEED := 6.5
const WORD_SPEED := 42.0
const CHAR_GAP := 4.0
const EAT_RADIUS := 18.0
const BANNER_SCALE := 1.05
const BANNER_CHAR_SPACING := 14.0
const WAVE_AMP := 4.0
const WAVE_FREQ := 1.55
const BELT_TAIL := 480.0

const TAGLINE := "CODING FOR THE MASSES NOT THE CLASSES"
const RIBBON_Y := 108.0
const RIBBON_SPEED := 92.0
const RIBBON_WAVE_AMP := 18.0
const RIBBON_WAVE_FREQ := 0.019
const RIBBON_WAVE_SPEED := 1.75

const PLASMA_SPEED := 2.4
const CRAWL_SPEED := 44.0
const CRAWL_LINE_SP := 34.0
const TERMINAL_SPEED := 30.0
const TERMINAL_LINE_SP := 25.0
const PANEL_LEFT := Rect2(28.0, 402.0, 584.0, 228.0)
const PANEL_RIGHT := Rect2(668.0, 402.0, 584.0, 228.0)
const LUCID_MUSIC := preload("res://lucid_music_player.gd")
const ABOUT_CANVAS := preload("res://about_vector_canvas.gd")
const AUDIO_ATTACK := 16.0
const AUDIO_RELEASE := 5.5

const FEATURE_CRAWL_LINES: PackedStringArray = [
	"VISUAL GASIC",
	"WHAT GDSCRIPT DOES NOT SHIP",
	"",
	"VB6 SYNTAX  AUTO EVENT WIRING",
	"CAPTION  LEFT  TOP  CONNECT",
	"TRY CATCH  SELECT CASE  WITH",
	"",
	"WHENEVER  REACTIVE WATCHERS",
	"VARIABLE CHANGES  AUTO FIRE",
	"",
	"PYIMPORT  REAL PYTHON LIBS",
	"NUMPY  JSON  ML FROM .VG CODE",
	"",
	"IMMEDIATE WINDOW  LIVE REPL",
	"EVAL AT RUNTIME  DATA BREAKPOINTS",
	"TIME TRAVEL DEBUG  PROFILER UI",
	"",
	"NARCEA AI PAIR  MCP SERVER",
	"GENERATE  THEN AUDIT THE MACHINE",
	"",
	"SYSTEM LEVEL  NOT JUST NODES",
	"VGPROCESS  SOCKETS  ODBC SQL",
	"GPS  SENSORS  ON ANDROID",
	"DECLARE FUNCTION LIB  NATIVE FFI",
	"",
	"PARALLEL FOR  TASK.RUN",
	"JIT VM  9-PASS OPTIMIZER",
	"VECTOR CANVAS  GPU SIMD",
]

const BENCHMARK_LOG_LINES: PackedStringArray = [
	"SPEED TESTS  AUG 2026  GODOT 4.6",
	"SAME TASK FOR VG AND GDSCRIPT",
	"LOWER MICROSECONDS = FINISH FASTER",
	"",
	"COMPUTE  12 MICROBENCHMARKS",
	"IDENTICAL CHECKSUM = FAIR TEST",
	"",
	"ARITHMETIC LOOPS",
	" VG 27US       GDSCRIPT 3756US",
	" 139X FASTER THAN GDSCRIPT",
	"FUNCTION CALLS",
	" VG 140US      GDSCRIPT 8448US",
	" 60X FASTER THAN GDSCRIPT",
	"STRING CONCAT",
	" VG 140US      GDSCRIPT 7257US",
	" 52X FASTER THAN GDSCRIPT",
	"BRANCHING",
	" VG 152US      GDSCRIPT 10354US",
	" 68X FASTER THAN GDSCRIPT",
	"SCORE  VG WINS 12/12 VS GDSCRIPT",
	"",
	"DRAW  9 CANVAS WORKLOADS",
	"HOW LONG GODOT _DRAW TAKES",
	"",
	"2500 FILLED RECTS",
	" VG 160US      GDSCRIPT 1078US",
	" CPP 110US     FASTEST RAW DRAW",
	" 7X FASTER THAN GDSCRIPT",
	"2500 OUTLINE RECTS",
	" VG 554US      GDSCRIPT 1467US",
	" CPP 371US",
	" 3X FASTER THAN GDSCRIPT",
	"500 RECTS X 120 FRAMES",
	" VG 25US       GDSCRIPT 144US",
	" CPP 25US      TIED WITH VG",
	"SCORE  VG WINS 9/9 VS GDSCRIPT",
	"",
	"VS C++  VG WINS STRING INTEROP",
	"CPP STILL LEADS RAW NUMERIC LOOPS",
]

const BACKSTORY_RAW := (
	"00000000000000000000000000000000000000000000000000"
	+ "It started with an elementary school role-playing game called SPACE that a friend had invented. "
	+ "I wanted a friend and agreed to play, but I did not know the rules. "
	+ "So I built a world out of whole cloth. "
	+ "I called it Narcea. It was an ancient planet where biology had merged with machines, "
	+ "governed by a subterranean planetary AI. "
	+ "I was its citizen, half-organic and half-cybernetic. "
	+ "Looking back now, I realize Narcea was a childhood metaphor for my autism. "
	+ "In a world of fluid human interaction, I felt mechanical. "
	+ "I processed data differently. I didn't understand casual interaction. "
	+ "I could not decrypt the unwritten rules of social instinct. "
	+ "My father even called me Robot as an affectionate nickname. "
	+ "I had different processing capabilities and perspectives. "
	+ "I leaned into it. "
	+ "My classmate and I quickly became best friends. "
	+ "Together we resolved to build games. "
	+ "He focused on the screen and art, while I became obsessed with the architecture, the hardware, and the logic. "
	+ "Visual Gasic was conceived in that sandbox. "
	+ "Today Narcean Technologies develops software outside standard paradigms. "
	+ "Visual Gasic is explicitly engineered for the AI era. "
	+ "Programming has shifted from manual input to algorithmic generation and curation. "
	+ "But code generated by an AI cannot go unchecked; to do so invites catastrophic security failures. "
	+ "We must be able to audit the machine. "
	+ "We use BASIC syntax because it remains the zenith of human-readable code. "
	+ "It was not designed for compiler optimization or developer elitism. "
	+ "It was designed for immediate human comprehension."
)

var canvas: VGVectorCanvas2D
var t: float = 0.0
var is_headless: bool = false
var _has_path_text: bool = false
var _has_wave_text: bool = false

var perimeter: float = 0.0
var oval_a: float = 0.0
var oval_b: float = 0.0
var letter_stream: String = ""
var belt_letters: Array = []
var next_letter_idx: int = 0
var pac_s: float = 0.0
var chomp: float = 0.0
var ready_to_continue: bool = false
var spark_phase: PackedFloat32Array = PackedFloat32Array()
var _showcase_frozen := false
var _panel_scroll_t := -1.0  # < 0 = portal preview; >= 0 = fullscreen scroll elapsed
var _crawl_lines: PackedStringArray = PackedStringArray()
var _lucid_music: Node = null
var movie_mode := false
var _audio_bass := 0.0
var _audio_mid := 0.0
var _audio_treble := 0.0
var _audio_energy := 0.0


func set_showcase_frozen(frozen: bool) -> void:
	_showcase_frozen = frozen


func begin_portal_play() -> void:
	_activate_live_content()


func reset_for_portal() -> void:
	_panel_scroll_t = -1.0
	_stop_lucid_music()


func resume_portal_preview() -> void:
	_showcase_frozen = false
	_panel_scroll_t = -1.0
	_stop_lucid_music()


func freeze_showcase_frame() -> void:
	_showcase_frozen = true


func movie_play_complete() -> bool:
	return ready_to_continue


func _activate_live_content() -> void:
	_showcase_frozen = false
	if _panel_scroll_t < 0.0:
		_panel_scroll_t = 0.0
	_start_lucid_music()


func _ensure_live_content() -> void:
	if is_headless or _showcase_frozen:
		return
	if not _is_embedded_in_carrier():
		return
	if _panel_scroll_t < 0.0:
		_panel_scroll_t = 0.0
	_start_lucid_music()


func _ready() -> void:
	is_headless = DisplayServer.get_name() == "headless"
	movie_mode = OS.has_feature("movie")
	set_process(true)
	oval_a = _edge_w() * 0.5
	oval_b = _edge_h() * 0.5
	perimeter = _calc_oval_perimeter()
	_ensure_viewport_camera()
	_add_fallback_background()
	if ClassDB.class_exists("VGVectorCanvas2D"):
		canvas = ABOUT_CANVAS.new()
		canvas.name = "VectorCanvas"
		canvas.z_index = 10
		canvas.visible = true
		add_child(canvas)
		_has_path_text = canvas.has_method("DrawVectorTextPath")
		_has_wave_text = canvas.has_method("DrawVectorTextWave")
	else:
		push_error("AboutVG: VGVectorCanvas2D not available — is the Visual Gasic extension loaded?")
	letter_stream = _build_letter_stream()
	_init_sparks()
	_seed_belt()
	for line in FEATURE_CRAWL_LINES:
		if not line.is_empty():
			_crawl_lines.append(line)
	_setup_lucid_music()
	if not _is_embedded_in_carrier():
		_panel_scroll_t = 0.0
		_start_lucid_music()
	if is_headless and not _is_embedded_in_carrier():
		await get_tree().process_frame
		get_tree().quit()


func _init_sparks() -> void:
	spark_phase.resize(48)
	for i in spark_phase.size():
		spark_phase[i] = randf() * TAU


func _add_fallback_background() -> void:
	var bg_layer := CanvasLayer.new()
	bg_layer.layer = -10
	bg_layer.name = "FallbackBG"
	add_child(bg_layer)
	var rect := ColorRect.new()
	rect.set_anchors_preset(Control.PRESET_FULL_RECT)
	rect.mouse_filter = Control.MOUSE_FILTER_IGNORE
	rect.color = Color(0.008, 0.012, 0.028, 1.0)
	bg_layer.add_child(rect)


func _ensure_viewport_camera() -> void:
	if get_viewport() is not SubViewport:
		return
	var cam := Camera2D.new()
	cam.name = "ViewportCamera"
	cam.position = Vector2(CX, CY)
	add_child(cam)
	cam.make_current()


func _flush_canvas() -> void:
	if canvas == null:
		return
	canvas.Render()


func _setup_lucid_music() -> void:
	if is_headless:
		return
	if _is_embedded_in_carrier():
		_lucid_music = _find_carrier_lucid_music()
		if _lucid_music == null:
			push_warning("AboutVG: embedded but carrier LucidMusicPlayer not found")
		return
	_lucid_music = LUCID_MUSIC.new()
	add_child(_lucid_music)


func _find_carrier_lucid_music() -> Node:
	var carrier := get_viewport().get_parent() if get_viewport() else null
	if carrier and carrier.get("_lucid_music"):
		return carrier.get("_lucid_music")
	return null


func _start_lucid_music() -> void:
	if _lucid_music == null:
		return
	if _lucid_music.is_node_ready():
		if _lucid_music.has_method("start_default"):
			_lucid_music.start_default()
		else:
			_lucid_music.start()
	else:
		_lucid_music.ready.connect(func() -> void:
			if _lucid_music.has_method("start_default"):
				_lucid_music.start_default()
			else:
				_lucid_music.start()
		, CONNECT_ONE_SHOT)


func _panel_scroll_time() -> float:
	if _panel_scroll_t >= 0.0:
		return _panel_scroll_t
	if _showcase_frozen or is_headless:
		return 0.0
	return t


func _stop_lucid_music() -> void:
	if _lucid_music and _lucid_music.has_method("stop"):
		_lucid_music.stop()
	_audio_bass = 0.0
	_audio_mid = 0.0
	_audio_treble = 0.0
	_audio_energy = 0.0


func _update_audio_reactivity(delta: float) -> void:
	var playing: bool = false
	var bus_idx := -1
	if _lucid_music != null:
		if _lucid_music.has_method("is_playing"):
			playing = bool(_lucid_music.call("is_playing"))
		bus_idx = int(_lucid_music.get("bus_index"))
	var target_bass := 0.0
	var target_mid := 0.0
	var target_treble := 0.0
	if playing and bus_idx >= 0:
		var spectrum := AudioServer.get_bus_effect_instance(
			bus_idx, 0
		) as AudioEffectSpectrumAnalyzerInstance
		if spectrum:
			target_bass = _spectrum_level(spectrum, 28.0, 160.0, 9.0)
			target_mid = _spectrum_level(spectrum, 160.0, 2200.0, 11.0)
			target_treble = _spectrum_level(spectrum, 2200.0, 14000.0, 13.0)
	var rate := AUDIO_ATTACK if playing else AUDIO_RELEASE
	var smooth := 1.0 - exp(-delta * rate)
	_audio_bass = lerpf(_audio_bass, target_bass, smooth)
	_audio_mid = lerpf(_audio_mid, target_mid, smooth)
	_audio_treble = lerpf(_audio_treble, target_treble, smooth)
	_audio_energy = clampf(_audio_bass * 0.55 + _audio_mid * 0.3 + _audio_treble * 0.15, 0.0, 1.35)


func _spectrum_level(
		spectrum: AudioEffectSpectrumAnalyzerInstance,
		from_hz: float,
		to_hz: float,
		gain: float
	) -> float:
	var mag := spectrum.get_magnitude_for_frequency_range(
		from_hz,
		to_hz,
		AudioEffectSpectrumAnalyzerInstance.MAGNITUDE_AVERAGE
	)
	var level := sqrt(mag.x * mag.x + mag.y * mag.y) * gain
	return clampf(level, 0.0, 1.35)


func _exit_tree() -> void:
	if not _is_embedded_in_carrier():
		_stop_lucid_music()


func _build_letter_stream() -> String:
	return BACKSTORY_RAW.replace("—", "-").strip_edges().to_upper()


func _letter_step(ch: String) -> float:
	if ch == " ":
		return _char_step() * 0.55
	return _char_step()


func _seed_belt() -> void:
	belt_letters.clear()
	var s := _normalize_near(pac_s + 36.0, pac_s)
	var guard := 0
	while _belt_span() < BELT_TAIL and guard < 1200:
		if letter_stream.is_empty():
			break
		var ch: String = letter_stream.substr(next_letter_idx, 1)
		next_letter_idx = (next_letter_idx + 1) % letter_stream.length()
		belt_letters.append({"ch": ch, "s": s})
		s += _letter_step(ch) + CHAR_GAP
		guard += 1


func _spawn_letter_at(s_pos: float) -> void:
	if letter_stream.is_empty():
		return
	var ch: String = letter_stream.substr(next_letter_idx, 1)
	next_letter_idx = (next_letter_idx + 1) % letter_stream.length()
	belt_letters.append({"ch": ch, "s": _normalize_near(s_pos, pac_s)})


func _gap_to_pac(s_char: float) -> float:
	return fmod(_perim_pos(s_char) - pac_s + perimeter, perimeter)


func _belt_span() -> float:
	if belt_letters.is_empty():
		return 0.0
	var min_s := _normalize_near(float(belt_letters[0]["s"]), pac_s)
	var max_s := min_s
	for entry in belt_letters:
		var v := _normalize_near(float(entry["s"]), pac_s)
		min_s = minf(min_s, v)
		max_s = maxf(max_s, v)
	return max_s - min_s


func _tail_max_s() -> float:
	var best := _normalize_near(float(belt_letters[0]["s"]), pac_s)
	for entry in belt_letters:
		best = maxf(best, _normalize_near(float(entry["s"]), pac_s))
	return best


func _tail_letter_step() -> float:
	if letter_stream.is_empty():
		return _char_step()
	var ch: String = letter_stream.substr(next_letter_idx, 1)
	return _letter_step(ch) + CHAR_GAP


func _update_belt(delta: float) -> void:
	pac_s = fmod(pac_s + PACMAN_SPEED * delta, perimeter)
	var step := WORD_SPEED * delta

	var i := 0
	while i < belt_letters.size():
		var new_s: float = float(belt_letters[i]["s"]) - step
		belt_letters[i]["s"] = _normalize_near(new_s, pac_s)
		var gap := _gap_to_pac(float(belt_letters[i]["s"]))
		if gap <= EAT_RADIUS and gap < perimeter * 0.5:
			belt_letters.remove_at(i)
			chomp = 1.0
		else:
			i += 1

	while belt_letters.size() < 1200 and _belt_span() < BELT_TAIL:
		var tail_s := _tail_max_s()
		_spawn_letter_at(tail_s + _tail_letter_step())


func _edge_w() -> float:
	return SW - BORDER_INSET * 2.0


func _edge_h() -> float:
	return SH - BORDER_INSET * 2.0


func _perim_pos(s: float) -> float:
	var p := fmod(s, perimeter)
	if p < 0.0:
		p += perimeter
	return p


func _normalize_near(s: float, ref: float) -> float:
	var p := s
	while p < ref - perimeter * 0.5:
		p += perimeter
	while p > ref + perimeter * 0.5:
		p -= perimeter
	return p


func _char_step() -> float:
	return 10.0 * BANNER_SCALE + BANNER_CHAR_SPACING


func _calc_oval_perimeter() -> float:
	var a := oval_a
	var b := oval_b
	return PI * (3.0 * (a + b) - sqrt((3.0 * a + b) * (a + 3.0 * b)))


func _ds_dtheta(theta: float) -> float:
	var c := cos(theta)
	var sn := sin(theta)
	return sqrt(oval_a * oval_a * c * c + oval_b * oval_b * sn * sn)


func _theta_from_s(s: float) -> float:
	var target := _perim_pos(s)
	var acc := 0.0
	var theta := 0.0
	const STEPS := 480
	var dth := TAU / float(STEPS)
	for _i in STEPS:
		var seg := _ds_dtheta(theta) * dth
		if acc + seg >= target:
			var frac := (target - acc) / maxf(seg, 0.001)
			return theta + frac * dth
		acc += seg
		theta += dth
	return 0.0


func _path_frame(s: float) -> Dictionary:
	var theta := _theta_from_s(s)
	var pos := Vector2(CX + oval_a * sin(theta), CY - oval_b * cos(theta))
	var tangent := atan2(oval_b * sin(theta), oval_a * cos(theta))
	return {"pos": pos, "angle": tangent, "read_angle": tangent}


func _path_normal(angle: float) -> Vector2:
	return Vector2(-sin(angle), cos(angle))


func _process(delta: float) -> void:
	_ensure_live_content()
	if not _showcase_frozen:
		t += delta
		_update_belt(delta)
		chomp = maxf(0.0, chomp - delta * 3.5)
		ready_to_continue = belt_letters.is_empty()
		if _panel_scroll_t >= 0.0:
			_panel_scroll_t += delta
	if not is_headless:
		_update_audio_reactivity(delta)
	if canvas == null:
		return

	canvas.Clear()
	_draw_background()
	_draw_sparks()
	_draw_corner_frames()
	_draw_center_panel()
	_draw_tagline_scroller()
	_draw_conclusion_banner()
	_draw_conclusion_subtitle()
	_draw_helix_logo()
	_draw_lower_info_panels()
	_draw_border_words()
	_draw_pacman()
	_draw_prompt()
	_flush_canvas()


func _estimate_word_width(text: String, scale: float, spacing: float) -> float:
	var width := 0.0
	for i in text.length():
		width += 10.0 * scale
		if i < text.length() - 1:
			width += spacing
	return width


func _draw_background() -> void:
	canvas.call(
		"DrawRect",
		Rect2(0.0, 0.0, SW, SH),
		0.0,
		Color(0, 0, 0, 0),
		true,
		Color(0.008, 0.012, 0.028, 1.0)
	)

	var plasma_spd := t * PLASMA_SPEED * (
		1.0 + sin(t * 0.08) * 0.4 + _audio_mid * 0.42 + _audio_bass * 0.18
	)
	var plasma_fade := clampf(0.22 + _audio_energy * 0.34 + _audio_bass * 0.14, 0.18, 0.72)
	canvas.call("DrawPlasmaCells", 48, 27, plasma_spd, plasma_fade, SW / 48.0, SH / 27.0, 0)
	canvas.call("DrawPlasmaCells", 48, 27, plasma_spd, plasma_fade, SW / 48.0, SH / 27.0, 1)

	var glow := 0.32 + sin(t * 1.8) * 0.1 + _audio_energy * 0.55
	var blob_hue := fmod(0.58 + _audio_treble * 0.12 - _audio_bass * 0.05, 1.0)
	var outer_col := Color.from_hsv(blob_hue, 0.72, 1.0, glow * 0.85)
	outer_col.r *= 0.35
	outer_col.g *= 0.55
	outer_col.b *= 1.0
	var inner_hue := fmod(blob_hue + 0.08 + _audio_mid * 0.06, 1.0)
	var inner_col := Color.from_hsv(inner_hue, 0.65, 1.0, glow * 0.5)
	inner_col.r *= 0.4
	inner_col.g *= 0.75
	inner_col.b *= 1.0
	var outer_r := 300.0 + _audio_bass * 95.0 + _audio_energy * 28.0
	var inner_r := 120.0 + _audio_treble * 52.0 + _audio_mid * 34.0
	var blob_center := Vector2(
		CX + sin(t * 1.35 + _audio_mid * 2.4) * _audio_bass * 18.0,
		CY + 8.0 + cos(t * 1.05 + _audio_bass * 2.1) * _audio_bass * 14.0
	)
	canvas.call("SetAdditiveBlend", true)
	canvas.call(
		"DrawCircle",
		blob_center,
		outer_r,
		outer_col,
		false,
		Color(0, 0, 0, 0)
	)
	canvas.call(
		"DrawCircle",
		blob_center,
		inner_r,
		inner_col,
		false,
		Color(0, 0, 0, 0)
	)
	canvas.call("SetAdditiveBlend", false)


func _draw_sparks() -> void:
	canvas.call("SetAdditiveBlend", true)
	var beat := 0.35 + _audio_energy * 0.95
	for i in spark_phase.size():
		var phase := spark_phase[i]
		var orbit := 140.0 + _audio_bass * 48.0
		var px := fmod(float(i) * 97.0 + sin(t * 0.95 + phase) * orbit + SW * 0.5, SW)
		var py := fmod(float(i) * 53.0 + cos(t * 0.78 + phase * 1.3) * (orbit * 0.64) + SH * 0.48, SH)
		var tw: float = (0.35 + 0.65 * absf(sin(t * 3.4 + phase))) * (0.72 + beat * 0.55)
		var hue := fmod(float(i) * 0.07 + t * 0.11 + _audio_treble * 0.18, 1.0)
		var col := Color.from_hsv(hue, 0.55, 1.0, tw * 0.55)
		var spark_r := 1.2 + tw * 1.8 + _audio_treble * 2.4
		canvas.call("DrawCircle", Vector2(px, py), spark_r, col, true, col)
	canvas.call("SetAdditiveBlend", false)


func _draw_corner_frames() -> void:
	var pulse := 0.55 + 0.45 * sin(t * 2.1)
	var col := Color(0.25 * pulse, 0.72 * pulse, 1.0 * pulse, pulse * 0.75)
	var arm := 56.0
	var inset := 18.0
	var corners := [
		Vector2(inset, inset),
		Vector2(SW - inset, inset),
		Vector2(SW - inset, SH - inset),
		Vector2(inset, SH - inset),
	]
	var dirs := [
		[Vector2(arm, 0), Vector2(0, arm)],
		[Vector2(-arm, 0), Vector2(0, arm)],
		[Vector2(-arm, 0), Vector2(0, -arm)],
		[Vector2(arm, 0), Vector2(0, -arm)],
	]
	for i in corners.size():
		var c: Vector2 = corners[i]
		for d in dirs[i]:
			canvas.call("DrawLine", c, c + d, 2.2, col)


func _draw_helix_logo() -> void:
	var helix_y := CY + 24.0
	# Dark under-stroke so orbit text stays legible over plasma and the banner.
	canvas.call("SetAdditiveBlend", false)
	canvas.call(
		"DrawVectorTextHelix",
		"NARCEA",
		CX,
		helix_y,
		t * 0.72,
		Color(0.02, 0.04, 0.08, 0.72),
		2.35,
		2.6,
		175.0,
		0.38,
		0.0,
		0.60,
		0.28,
		""
	)
	canvas.call(
		"DrawVectorTextHelix",
		"VISUAL GASIC",
		CX,
		helix_y,
		t * 0.55 + 1.7,
		Color(0.02, 0.04, 0.08, 0.68),
		1.95,
		2.35,
		140.0,
		0.35,
		0.0,
		0.45,
		0.24,
		""
	)
	canvas.call("SetAdditiveBlend", true)
	canvas.call(
		"DrawVectorTextHelix",
		"NARCEA",
		CX,
		helix_y,
		t * 0.72,
		Color(0.35, 0.82, 1.0, 0.62),
		2.25,
		2.15,
		175.0,
		0.38,
		0.0,
		0.60,
		0.28,
		""
	)
	canvas.call(
		"DrawVectorTextHelix",
		"VISUAL GASIC",
		CX,
		helix_y,
		t * 0.55 + 1.7,
		Color(0.95, 0.55, 1.0, 0.52),
		1.85,
		1.95,
		140.0,
		0.35,
		0.0,
		0.45,
		0.24,
		""
	)
	canvas.call("SetAdditiveBlend", false)


func _draw_center_panel() -> void:
	canvas.call(
		"DrawRect",
		Rect2(0.0, 0.0, SW, 52.0),
		0.0,
		Color(0, 0, 0, 0),
		true,
		Color(0.0, 0.0, 0.0, 0.48)
	)
	canvas.call(
		"DrawVectorTextCentered",
		Vector2(CX, 28.0),
		"ABOUT VISUAL GASIC  |  NARCEAN TECHNOLOGIES  |  5.4.0-BETA1",
		Color(0.55, 0.95, 1.0, 0.96),
		1.35,
		1.2,
		1.6,
		""
	)


func _tagline_scroll_width(scale: float, spacing: float) -> float:
	return _estimate_word_width(TAGLINE, scale, spacing)


func _draw_tagline_scroller() -> void:
	if not _has_wave_text:
		return

	var scale := 2.15
	var spacing := 2.0
	var width := _tagline_scroll_width(scale, spacing)
	var gap := 140.0
	var period := width + gap
	var x0 := fmod(-t * RIBBON_SPEED, period)
	var pulse := 0.78 + 0.22 * sin(t * 2.1)
	var col := Color(0.3 * pulse, 0.92 * pulse, 1.0 * pulse, 0.9 * pulse)

	canvas.call(
		"DrawRect",
		Rect2(0.0, RIBBON_Y - 28.0, SW, 56.0),
		0.0,
		Color(0, 0, 0, 0),
		true,
		Color(0.0, 0.0, 0.0, 0.28)
	)
	canvas.call("SetAdditiveBlend", true)
	for i in 3:
		var x_off: float = x0 + float(i) * period
		canvas.call(
			"DrawVectorTextWave",
			TAGLINE,
			x_off,
			RIBBON_Y,
			t,
			col,
			scale,
			2.2,
			RIBBON_WAVE_AMP,
			RIBBON_WAVE_FREQ,
			RIBBON_WAVE_SPEED,
			spacing,
			false,
			""
		)
	canvas.call("SetAdditiveBlend", false)


func _draw_conclusion_banner() -> void:
	var pulse := 0.62 + 0.38 * sin(t * 2.4)
	var banner_y := CY - 18.0

	canvas.call(
		"DrawRect",
		Rect2(CX - 420.0, banner_y - 36.0, 840.0, 84.0),
		0.0,
		Color(0, 0, 0, 0),
		true,
		Color(0.0, 0.0, 0.0, 0.42 * pulse)
	)

	canvas.call("SetAdditiveBlend", true)
	canvas.call(
		"DrawVectorTextCentered",
		Vector2(CX, banner_y - 10.0),
		"THIS CONCLUDES THE ABOUT DEMO",
		Color(0.25 * pulse, 0.85 * pulse, 1.0 * pulse, pulse * 0.55),
		2.35,
		2.05,
		2.6,
		""
	)
	canvas.call("SetAdditiveBlend", false)
	canvas.call(
		"DrawVectorTextCentered",
		Vector2(CX, banner_y - 10.0),
		"THIS CONCLUDES THE ABOUT DEMO",
		Color(1.0, 0.98, 0.92, 0.96),
		2.2,
		1.85,
		2.6,
		""
	)


func _draw_conclusion_subtitle() -> void:
	var banner_y := CY - 18.0
	canvas.call(
		"DrawVectorTextCentered",
		Vector2(CX, banner_y + 30.0),
		"ZERO EXTERNAL ASSETS  |  PROCEDURAL SKY  |  CUSTOM GLSL SHADERS",
		Color(0.55, 0.82, 1.0, 0.88),
		0.95,
		1.15,
		1.2,
		""
	)


func _draw_lower_info_panels() -> void:
	_draw_feature_crawl(PANEL_LEFT)
	_draw_benchmark_terminal(PANEL_RIGHT)


func _draw_panel_chrome(panel: Rect2, title: String, accent: Color) -> void:
	canvas.call(
		"DrawRect",
		panel,
		0.0,
		Color(0, 0, 0, 0),
		true,
		Color(0.01, 0.015, 0.035, 0.62)
	)
	var header := Rect2(panel.position.x, panel.position.y, panel.size.x, 20.0)
	canvas.call(
		"DrawRect",
		header,
		0.0,
		Color(0, 0, 0, 0),
		true,
		Color(accent.r * 0.12, accent.g * 0.12, accent.b * 0.12, 0.88)
	)
	canvas.call(
		"DrawVectorText",
		panel.position + Vector2(10.0, 14.0),
		title,
		Color(accent.r, accent.g, accent.b, 0.92),
		0.68,
		1.0,
		"left",
		0.0,
		""
	)
	var p0 := panel.position
	var p1 := panel.position + Vector2(panel.size.x, 0.0)
	var p2 := panel.position + panel.size
	var p3 := panel.position + Vector2(0.0, panel.size.y)
	var edge := Color(accent.r, accent.g, accent.b, 0.38)
	canvas.call("DrawLine", p0, p1, 1.2, edge)
	canvas.call("DrawLine", p1, p2, 1.2, edge)
	canvas.call("DrawLine", p2, p3, 1.2, edge)
	canvas.call("DrawLine", p3, p0, 1.2, edge)


func _panel_content_fade(content: Rect2, y: float, top_fade: float, bot_fade: float) -> float:
	var top := content.position.y
	var bot := content.position.y + content.size.y
	if y < top or y > bot:
		return 0.0
	var a := smoothstep(top, top + top_fade, y)
	a *= smoothstep(bot, bot - bot_fade, y)
	return a



func _draw_feature_crawl(panel: Rect2) -> void:
	_draw_panel_chrome(panel, "FEATURES", Color(0.98, 0.86, 0.38))
	var scroll_t := _panel_scroll_time()
	var body := Rect2(panel.position.x, panel.position.y + 22.0, panel.size.x, panel.size.y - 22.0)
	var vanish_x := body.position.x + body.size.x * 0.5
	var line_count := _crawl_lines.size()
	if line_count == 0:
		return
	var scroll := fmod(scroll_t * CRAWL_SPEED, float(line_count) * CRAWL_LINE_SP)
	var content_top := body.position.y
	var content_bot := body.position.y + body.size.y
	var anchor := content_bot + 36.0 - scroll
	var k_lo := int(floor((content_top - CRAWL_LINE_SP - anchor) / CRAWL_LINE_SP))
	var k_hi := int(ceil((content_bot + CRAWL_LINE_SP - anchor) / CRAWL_LINE_SP))

	for k in range(k_lo, k_hi + 1):
		var y := anchor + float(k) * CRAWL_LINE_SP
		var idx := posmod(k, line_count)
		var crawl_line: String = _crawl_lines[idx]
		var fade := _panel_content_fade(body, y, 36.0, 48.0)
		if fade <= 0.01:
			continue
		var depth := clampf((y - body.position.y) / maxf(body.size.y - 8.0, 1.0), 0.0, 1.0)
		var scale := lerpf(0.42, 1.08, depth)
		var col := Color(0.98, 0.88, 0.42, fade * 0.94)
		canvas.call(
			"DrawVectorTextCentered",
			Vector2(vanish_x, y),
			crawl_line,
			col,
			scale,
			1.25,
			1.0,
			""
		)


func _draw_benchmark_terminal(panel: Rect2) -> void:
	_draw_panel_chrome(panel, "BENCHMARKS", Color(0.38, 0.98, 0.68))
	var scroll_t := _panel_scroll_time()
	var body := Rect2(panel.position.x, panel.position.y + 22.0, panel.size.x, panel.size.y - 22.0)
	var x := body.position.x + 12.0
	var line_count := BENCHMARK_LOG_LINES.size()
	var scroll := fmod(scroll_t * TERMINAL_SPEED, float(line_count) * TERMINAL_LINE_SP)
	var content_top := body.position.y
	var content_bot := body.position.y + body.size.y
	var anchor := content_bot + 8.0 - scroll
	var k_lo := int(floor((content_top - TERMINAL_LINE_SP - anchor) / TERMINAL_LINE_SP))
	var k_hi := int(ceil((content_bot + TERMINAL_LINE_SP - anchor) / TERMINAL_LINE_SP))

	for k in range(k_lo, k_hi + 1):
		var y := anchor + float(k) * TERMINAL_LINE_SP
		var idx := posmod(k, line_count)
		var line: String = BENCHMARK_LOG_LINES[idx]
		if line.is_empty():
			continue
		var fade := _panel_content_fade(body, y, 28.0, 36.0)
		if fade <= 0.01:
			continue
		var col: Color
		if line.find("X FASTER") >= 0 or line.begins_with("SCORE"):
			col = Color(0.42, 1.0, 0.68, fade * 0.95)
		elif line.begins_with(" VG ") or line.begins_with(" CPP"):
			col = Color(0.72, 0.95, 1.0, fade * 0.9)
		elif line.find("SUITE") >= 0 or line.begins_with("VS C++") or line.begins_with("SPEED") or line.begins_with("SAME") or line.begins_with("IDENTICAL") or line.begins_with("HOW LONG") or line.begins_with("COMPUTE") or line.begins_with("DRAW ") or line.begins_with("CPP STILL"):
			col = Color(0.98, 0.86, 0.38, fade * 0.92)
		else:
			col = Color(0.55, 0.88, 1.0, fade * 0.78)
		canvas.call(
			"DrawVectorText",
			Vector2(x, y),
			line,
			col,
			0.88,
			1.15,
			"left",
			0.0,
			""
		)


func _draw_border_words() -> void:
	if belt_letters.is_empty():
		return

	var palette: Array[Color] = [
		Color(0.45, 1.0, 1.0, 1.0),
		Color(1.0, 0.92, 0.35, 1.0),
		Color(0.55, 1.0, 0.65, 1.0),
		Color(1.0, 0.65, 0.95, 1.0),
	]
	var li := 0
	for entry in belt_letters:
		var ch: String = entry["ch"]
		if ch == " ":
			continue
		var s_char: float = _normalize_near(float(entry["s"]), pac_s)
		var frame := _path_frame(s_char)
		var cw_angle: float = frame.angle
		var read_angle: float = frame.get("read_angle", cw_angle)
		var wave_phase: float = t * WAVE_FREQ + float(li) * 0.07
		var col: Color = palette[li % palette.size()]
		col.a = 0.94
		var wave_off: float = sin(wave_phase) * WAVE_AMP
		var origin: Vector2 = frame.pos + _path_normal(cw_angle) * wave_off

		if _has_path_text:
			canvas.call(
				"DrawVectorTextPath",
				origin,
				cw_angle,
				read_angle,
				ch,
				col,
				BANNER_SCALE,
				1.65,
				0.0,
				""
			)
		else:
			canvas.call(
				"DrawVectorText",
				origin,
				ch,
				col,
				BANNER_SCALE,
				1.65,
				"left",
				0.0,
				""
			)
		li += 1


func _draw_pacman() -> void:
	var frame := _path_frame(pac_s)
	var pos: Vector2 = frame.pos
	var angle: float = frame.angle
	var mouth: float = 0.22 + chomp * 0.55 + absf(sin(t * 9.0)) * 0.12
	var radius := 14.0

	canvas.call("SetAdditiveBlend", false)
	canvas.call(
		"DrawCircle",
		pos,
		radius,
		Color(1.0, 0.88, 0.0, 1.0),
		true,
		Color(1.0, 0.88, 0.0, 1.0)
	)

	var p1 := pos + Vector2(cos(angle + mouth), sin(angle + mouth)) * radius * 1.05
	var p2 := pos + Vector2(cos(angle - mouth), sin(angle - mouth)) * radius * 1.05
	var pts := PackedVector2Array([pos, p1, p2, pos])
	canvas.call(
		"DrawPolyline",
		pts,
		1.0,
		Color(0.008, 0.012, 0.028, 1.0),
		true,
		Color(0.008, 0.012, 0.028, 1.0),
		true
	)

	if chomp > 0.05:
		canvas.call("SetAdditiveBlend", true)
		canvas.call(
			"DrawCircle",
			pos,
			radius * (1.0 + chomp * 0.35),
			Color(1.0, 0.95, 0.2, chomp * 0.45),
			false,
			Color(0, 0, 0, 0)
		)
		canvas.call("SetAdditiveBlend", false)


func _draw_prompt() -> void:
	if is_headless:
		return
	var pulse := 0.55 + 0.45 * sin(t * 3.2)
	var glow_a := 0.35 + pulse * 0.55
	canvas.call("SetAdditiveBlend", true)
	canvas.call(
		"DrawVectorTextCentered",
		Vector2(CX, SH - 52.0),
		"PRESS ANY KEY TO CONTINUE",
		Color(0.4 * glow_a, 1.0 * glow_a, 0.85 * glow_a, glow_a),
		1.55,
		1.35,
		1.8,
		""
	)
	canvas.call(
		"DrawVectorTextCentered",
		Vector2(CX, SH - 52.0),
		"PRESS ANY KEY TO CONTINUE",
		Color(1.0, 1.0, 0.75, pulse * 0.35),
		1.58,
		1.5,
		1.8,
		""
	)
	canvas.call("SetAdditiveBlend", false)


func _unhandled_input(event: InputEvent) -> void:
	if movie_mode:
		return
	if event is InputEventKey and event.pressed:
		match event.keycode:
			KEY_ESCAPE:
				if not _is_embedded_in_carrier():
					get_tree().quit()
			_:
				if not _is_embedded_in_carrier() and (ready_to_continue or not is_headless):
					get_tree().change_scene_to_file(NEXT_SCENE)


func _is_embedded_in_carrier() -> bool:
	if get_viewport() is SubViewport:
		return true
	return has_meta("vg_portal_embedded") and bool(get_meta("vg_portal_embedded"))
