@tool
## working_nodes_codegen.gd
## Converts a Working Nodes graph (serialized Dictionary) into:
##   • VG code  (.vg)  — executes in the VisualGasic interpreter
##   • 2D scene (.tscn) + companion .vg script
##   • 3D scene (.tscn) + companion .vg script
##
## All public methods are static so they can be called without an instance.
class_name working_nodes_codegen
extends RefCounted


# ─── Public API ──────────────────────────────────────────────────────────────

## Generate VG code from a Working Nodes graph dictionary.
## data  – the parsed JSON dict (from a .wnodes save).
## Returns the full VG code as a String.
static func generate_vg_code(data: Dictionary) -> String:
	var gen := _VGGen.new()
	return gen.build(data)


## Generate a Godot 2D scene (.tscn text) from a Working Nodes graph.
## vg_script_path – the res:// path where the companion .vg file will be saved.
## root_type     – the Godot node type for the root (default "Node2D").
## Returns the TSCN file content as a String.
static func generate_scene_2d_tscn(data: Dictionary, vg_script_path: String, root_type: String = "Node2D") -> String:
	var gen := _SceneGen.new()
	return gen.build_2d(data, vg_script_path, root_type)


## Generate a Godot 3D scene (.tscn text) from a Working Nodes graph.
## vg_script_path – the res:// path where the companion .vg file will be saved.
## root_type     – the Godot node type for the root (default "Node3D").
## Returns the TSCN file content as a String.
static func generate_scene_3d_tscn(data: Dictionary, vg_script_path: String, root_type: String = "Node3D") -> String:
	var gen := _SceneGen.new()
	return gen.build_3d(data, vg_script_path, root_type)


## Generate a GDScript (.gd) source file from a Working Nodes graph.
## Returns the full GDScript source as a String.
static func generate_gdscript(data: Dictionary) -> String:
	var gen := _GDScriptGen.new()
	return gen.build(data)


## Parse VG code (.vg source) back into a Working Nodes graph dictionary.
## Returns a dict compatible with the editor's _apply_loaded_data / _rebuild_node_from_dict.
static func parse_vg_to_graph_data(vg_code: String) -> Dictionary:
	var parser := _VGParser.new()
	return parser.parse(vg_code)


## Derive a clean identifier (no spaces, starts with letter) from a raw string.
static func sanitize_name(raw: String, fallback: String = "Node") -> String:
	var out := ""
	for i in raw.length():
		var c := raw[i]
		if c.is_valid_identifier() or (i > 0 and c >= "0" and c <= "9"):
			out += c
		elif c == " " or c == "_":
			out += "_"
	if out.is_empty():
		return fallback
	if out[0] >= "0" and out[0] <= "9":
		out = "_" + out
	return out


# ─── VG Code Generator ───────────────────────────────────────────────────────

class _VGGen:
	var _nodes: Dictionary = {}     # node_name -> node_dict
	var _conns: Array = []          # connection dicts
	var _groups: Dictionary = {}    # group_id -> group_dict
	var _lines: PackedStringArray = PackedStringArray()

	func build(data: Dictionary) -> String:
		_nodes = {}
		_conns = []
		_groups = {}
		_lines = PackedStringArray()

		# ── Normalise node list ───────────────────────────────────────────
		for nd in data.get("nodes", []):
			var n_name: String = str(nd.get("name", nd.get("title", "WN_0")))
			# Prefer "kind" (fallback editor) over "type" (simple editor)
			var n_kind: String = str(nd.get("kind", nd.get("type", "action"))).capitalize()
			var entry: Dictionary = nd.duplicate()
			entry["_kind"] = n_kind
			entry["_name"] = n_name
			_nodes[n_name] = entry

		_conns = data.get("connections", [])
		_groups = {}
		for g in data.get("groups", []):
			_groups[int(g.get("id", 0))] = g

		# ── Header comment ────────────────────────────────────────────────
		_w("' Generated by Working Nodes — VisualGasic")
		_w("' Edit this file in the VG Code Editor, then press Run to execute.")
		_w("")

		# ── Variable declarations ─────────────────────────────────────────
		var var_nodes := _nodes_of_kind("Variable")
		if not var_nodes.is_empty():
			_w("' --- Variables ---")
			for nd in var_nodes:
				_emit_variable_decl(nd)
			_w("")

		# ── Math helper functions (top-level, called from event subs) ─────
		var math_nodes := _nodes_of_kind("Math")
		var bm_nodes   := _nodes_of_kind("Boolmath")
		var vm_nodes   := _nodes_of_kind("Vectormath")
		var mr_nodes   := _nodes_of_kind("Maprange")
		var rv_nodes   := _nodes_of_kind("Randomvalue")
		var cmp_nodes  := _nodes_of_kind("Compare")

		if not (math_nodes + bm_nodes + vm_nodes + mr_nodes + rv_nodes + cmp_nodes).is_empty():
			_w("' --- Math / Utility Functions ---")
			for nd in math_nodes:   _emit_math_function(nd)
			for nd in bm_nodes:     _emit_boolmath_function(nd)
			for nd in vm_nodes:     _emit_vectormath_function(nd)
			for nd in mr_nodes:     _emit_maprange_function(nd)
			for nd in rv_nodes:     _emit_randomvalue_function(nd)
			for nd in cmp_nodes:    _emit_compare_function(nd)
			_w("")

		# ── User-defined functions ────────────────────────────────────────
		var fn_nodes := _nodes_of_kind("Function")
		if not fn_nodes.is_empty():
			_w("' --- Custom Functions ---")
			for nd in fn_nodes:
				_emit_function_node(nd)
			_w("")

		# ── Event handlers ────────────────────────────────────────────────
		# Simple editor uses lowercase "event"; fallback uses "Event"
		# Trigger-style editor uses "on_start" → capitalized to "On Start"
		var event_kinds := ["Event", "Timedevent", "Collisiontrigger", "On Start",
							"On Frame", "On Input", "On Collision"]
		var event_nodes: Array = []
		for kind in event_kinds:
			event_nodes.append_array(_nodes_of_kind(kind))

		if event_nodes.is_empty():
			# No explicit event nodes — wrap all actions in Form_Load
			_w("Sub Form_Load()")
			_w("    ' No Event nodes found; all actions placed here.")
			var all_actions := _nodes_of_kind("Action") + _nodes_of_kind("Trigger")
			for nd in all_actions:
				_emit_action_call(nd, "    ")
			_w("End Sub")
		else:
			for nd in event_nodes:
				_emit_event_sub(nd)

		# ── Action subs (implementations) ────────────────────────────────
		var action_kinds := [
			"Action", "Trigger", "Movegroup", "Rotategroup", "Spawntrigger",
			"Alphafade", "Togglegroup", "Pulseeffect", "Followtarget",
			"Cameracontrol", "Colorchannel",
			# New trigger-style action types:
			"Move", "Rotate", "Scale", "Alpha", "Color Trigger",
			"Pulse", "Spawn", "Stop", "Toggle", "Follow",
			"Shake", "Play Sfx", "Animate",
		]
		var action_nodes: Array = []
		for kind in action_kinds:
			action_nodes.append_array(_nodes_of_kind(kind))

		if not action_nodes.is_empty():
			_w("")
			_w("' --- Action Implementations ---")
			for nd in action_nodes:
				_emit_action_sub(nd)

		# ── Condition helpers ─────────────────────────────────────────────
		var cond_nodes := _nodes_of_kind("Condition") + _nodes_of_kind("Switch")
		if not cond_nodes.is_empty():
			_w("")
			_w("' --- Condition Helpers ---")
			for nd in cond_nodes:
				_emit_condition_sub(nd)

		# ── Loop subs ─────────────────────────────────────────────────────
		var loop_nodes := _nodes_of_kind("Loop")
		if not loop_nodes.is_empty():
			_w("")
			_w("' --- Loop Helpers ---")
			for nd in loop_nodes:
				_emit_loop_sub(nd)

		return "\n".join(Array(_lines))

	# ─── Helpers ─────────────────────────────────────────────────────────────

	func _w(line: String) -> void:
		_lines.append(line)

	func _nodes_of_kind(kind: String) -> Array:
		var out: Array = []
		var lk := kind.to_lower()
		for n in _nodes.values():
			if str(n.get("_kind", "")).to_lower() == lk:
				out.append(n)
		return out

	func _safe_name(nd: Dictionary, fallback: String = "WNNode") -> String:
		var raw := str(nd.get("title", nd.get("_name", fallback)))
		return working_nodes_codegen.sanitize_name(raw, fallback)

	## Return a list of node dicts connected *from* node_name on any port.
	func _downstream_of(node_name: String) -> Array:
		var out: Array = []
		for c in _conns:
			if str(c.get("from", "")) == node_name:
				var tn := str(c.get("to", ""))
				if _nodes.has(tn):
					out.append(_nodes[tn])
		return out

	## Topological walk from an entry node; returns ordered list of nodes.
	func _exec_chain(start_name: String) -> Array:
		var ordered: Array = []
		var visited: Dictionary = {}
		var queue: Array = [start_name]
		while not queue.is_empty():
			var cur: String = queue.pop_front()
			if visited.has(cur):
				continue
			visited[cur] = true
			if _nodes.has(cur):
				ordered.append(_nodes[cur])
			for c in _conns:
				if str(c.get("from", "")) == cur:
					queue.push_back(str(c.get("to", "")))
		return ordered

	# ─── Variable declaration ─────────────────────────────────────────────────

	func _emit_variable_decl(nd: Dictionary) -> void:
		var vname := str(nd.get("var_name", _safe_name(nd, "myVar")))
		var vtype := str(nd.get("var_type", "Double"))
		var vg_type := _map_type(vtype)
		var title := str(nd.get("title", vname))
		_w("Dim " + vname + " As " + vg_type + "  ' Variable node: " + title)

	func _map_type(t: String) -> String:
		match t.to_lower():
			"float", "double": return "Double"
			"int", "integer":  return "Long"
			"bool", "boolean": return "Boolean"
			"string":          return "String"
			"vector2":         return "String"   # VG uses String for vectors
			"vector3":         return "String"
			"color":           return "String"
			_: return "Variant"

	# ─── Event sub ───────────────────────────────────────────────────────────

	func _emit_event_sub(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var ev_type := str(nd.get("event_type", nd.get("title", "On Start")))
		var sub_sig := _event_signature(ev_type, n_name)
		_w("")
		_w("' Event: " + str(nd.get("title", n_name)))
		_w(sub_sig)

		# Walk execution chain and emit calls
		var chain := _exec_chain(n_name)
		var indent := "    "
		for linked_nd in chain:
			if str(linked_nd.get("_name", "")) == n_name:
				continue
			var kind := str(linked_nd.get("_kind", "")).to_lower()
			match kind:
				"variable":
					pass  # already declared at top
				"condition":
					_emit_inline_condition(linked_nd, indent)
				"loop":
					_emit_inline_loop(linked_nd, indent)
				"sequence":
					_emit_inline_sequence(linked_nd, indent)
				"branch":
					_emit_inline_branch(linked_nd, indent)
				"cmp trig":
					_emit_inline_cmp_trig(linked_nd, indent)
				"input poll":
					_emit_inline_input_poll(linked_nd, indent)
				"math", "boolmath", "vectormath", "maprange", "randomvalue", "compare":
					pass  # called via function; only emit if result is used
				_:
					_emit_action_call(linked_nd, indent)

		_w("End Sub")

	func _event_signature(ev_type: String, n_name: String) -> String:
		var t := ev_type.to_lower()
		if "start" in t or "ready" in t or "load" in t:
			return "Sub Form_Load()"
		elif "process" in t or "update" in t or "frame" in t:
			return "Sub Form_Process(ByVal delta As Single)"  # runs every physics frame
		elif "timer" in t:
			return "Sub Timer1_Tick()"
		elif t == "on input":
			return "Sub Form_KeyDown(ByVal key As String)"
		elif "touch" in t or "click" in t or "input" in t:
			return "Sub Form_Click()"
		elif "signal" in t:
			return "Sub Form_Signal(ByVal signal_name As String)"
		elif "collision" in t:
			return "Sub Form_Collision(ByVal other As String)"
		elif "timed" in t:
			return "Sub WN_" + n_name.replace("WN_", "") + "_Tick()"
		else:
			var safe := working_nodes_codegen.sanitize_name(ev_type, "WNEvent")
			return "Sub " + safe + "_Event()"

	# ─── Inline condition ─────────────────────────────────────────────────────

	func _emit_inline_condition(nd: Dictionary, indent: String) -> void:
		var cmp_op := str(nd.get("compare_op", "=="))
		var cmp_val := str(nd.get("compare_value", "0"))
		var var_a := str(nd.get("var_a", "value"))
		_w(indent + "If " + var_a + " " + cmp_op + " " + cmp_val + " Then")
		var true_chain := _downstream_of(str(nd.get("_name", "")))
		for tn in true_chain:
			_emit_action_call(tn, indent + "    ")
		_w(indent + "End If")

	# ─── Inline loop ──────────────────────────────────────────────────────────

	func _emit_inline_loop(nd: Dictionary, indent: String) -> void:
		var count := int(nd.get("loop_count", 3))
		var loop_type := str(nd.get("loop_type", "For (count)")).to_lower()
		if "for" in loop_type and "each" not in loop_type:
			_w(indent + "Dim _i As Long")
			_w(indent + "For _i = 0 To " + str(count - 1) + " Step 1")
			var body_chain := _downstream_of(str(nd.get("_name", "")))
			for bn in body_chain:
				_emit_action_call(bn, indent + "    ")
			_w(indent + "Next _i")
		elif "while" in loop_type:
			_w(indent + "Do While True  ' condition loop from node: " + str(nd.get("title", "")))
			_w(indent + "    ' TODO: break when done")
			_w(indent + "Loop")
		elif "each" in loop_type:
			_w(indent + "' For Each loop — replace arr() with your array variable")
			_w(indent + "Dim _item As Variant")
			_w(indent + "For Each _item In arr()")
			_w(indent + "    ' process _item")
			_w(indent + "Next _item")

	# ─── Inline sequence ──────────────────────────────────────────────────────

	func _emit_inline_sequence(nd: Dictionary, indent: String) -> void:
		var prm  := nd.get("params", {})
		var intv := str(prm.get("Interval", "0.0"))
		_w(indent + "' Sequence: " + str(nd.get("title", "")) + "  (interval=" + intv + ")")
		var outputs := _downstream_of(str(nd.get("_name", "")))
		for i in outputs.size():
			var dn: Dictionary = outputs[i]
			if float(intv) > 0.0:
				_w(indent + "Call WN_Wait(" + str(float(intv) * i) + ")")
			_w(indent + "' Step " + str(i + 1) + ":")
			_emit_action_call(dn, indent)

	func _emit_inline_branch(nd: Dictionary, indent: String) -> void:
		var prm     := nd.get("params", {})
		var counter := str(prm.get("Counter", "score"))
		var op      := str(prm.get("Op",      ">="))
		var val     := str(prm.get("Value",   "0"))
		var n_name  := str(nd.get("_name", ""))
		_w(indent + "If " + counter + " " + _to_vg_op(op) + " " + val + " Then")
		for dn in _downstream_by_port(n_name, 0):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "Else")
		for dn in _downstream_by_port(n_name, 1):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "End If")

	func _emit_inline_cmp_trig(nd: Dictionary, indent: String) -> void:
		var prm    := nd.get("params", {})
		var a_name := str(prm.get("A",  "score"))
		var op     := str(prm.get("Op", ">"))
		var b_name := str(prm.get("B",  "0"))
		var n_name := str(nd.get("_name", ""))
		_w(indent + "If " + a_name + " " + _to_vg_op(op) + " " + b_name + " Then")
		for dn in _downstream_by_port(n_name, 0):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "Else")
		for dn in _downstream_by_port(n_name, 1):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "End If")

	func _to_vg_op(op: String) -> String:
		match op:
			"==": return "="
			"!=": return "<>"
			">=": return ">="
			"<=": return "<="
			">": return ">"
			"<": return "<"
			_:   return op

	func _downstream_by_port(node_name: String, from_port: int) -> Array:
		var out: Array = []
		for c in _conns:
			if str(c.get("from", "")) == node_name and int(c.get("from_port", 0)) == from_port:
				var tn := str(c.get("to", ""))
				if _nodes.has(tn):
					out.append(_nodes[tn])
		return out

	func _emit_inline_input_poll(nd: Dictionary, indent: String) -> void:
		var prm    := nd.get("params", {})
		var action := str(prm.get("Action", "move_right"))
		var mode   := str(prm.get("Mode",   "pressed")).to_lower()
		var n_name := str(nd.get("_name", ""))
		var vg_fn  := "IsActionPressed"
		if "just_pressed" in mode or "just pressed" in mode:
			vg_fn = "IsActionJustPressed"
		elif "just_released" in mode or "just released" in mode:
			vg_fn = "IsActionJustReleased"
		_w(indent + "If Input." + vg_fn + "(\"" + action + "\") Then")
		for dn in _downstream_by_port(n_name, 0):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "Else")
		for dn in _downstream_by_port(n_name, 1):
			_emit_action_call(dn, indent + "    ")
		_w(indent + "End If")

	func _emit_inline_delta_var(nd: Dictionary, indent: String) -> void:
		var prm   := nd.get("params", {})
		var vname := str(prm.get("Var",  "velY"))
		var op    := str(prm.get("Op",   "+=" ))
		var rate  := str(prm.get("Rate", "980"))
		match op:
			"+=": _w(indent + vname + " = " + vname + " + " + rate + " * delta")
			"-=": _w(indent + vname + " = " + vname + " - " + rate + " * delta")
			"*=": _w(indent + vname + " = " + vname + " * " + rate + " * delta")
			"=":  _w(indent + vname + " = " + rate + " * delta")
			_:   _w(indent + vname + " = " + vname + " + " + rate + " * delta")

	func _emit_action_call(nd: Dictionary, indent: String) -> void:
		# Breakpoint probe
		if nd.get("_breakpoint", false):
			_w(indent + "Print \">>> BREAKPOINT: " + str(nd.get("title", str(nd.get("_name","?")))) + "\"")
		var kind := str(nd.get("_kind", "")).to_lower()
		var n_name := str(nd.get("_name", "WN_0"))
		match kind:
			"action":
				var sub_n := "Action_" + n_name
				_w(indent + "Call " + sub_n + "()")
			"movegroup":
				var gid := str(nd.get("group_id", 1))
				var mx  := str(nd.get("move_x",  0))
				var my  := str(nd.get("move_y",  0))
				var dur := str(nd.get("duration", 0.0))
				_w(indent + "Call WN_MoveGroup(" + gid + ", " + mx + ", " + my + ", " + dur + ")")
			"rotategroup":
				var gid := str(nd.get("group_id", 1))
				var deg := str(nd.get("degrees",  0))
				var dur := str(nd.get("duration", 0.0))
				_w(indent + "Call WN_RotateGroup(" + gid + ", " + deg + ", " + dur + ")")
			"spawntrigger":
				var tgt := str(nd.get("target_group", 1))
				var delay := str(nd.get("delay", 0.0))
				_w(indent + "Call WN_SpawnTrigger(" + tgt + ", " + delay + ")")
			"alphafade":
				var gid := str(nd.get("group_id", 1))
				var opa := str(nd.get("opacity",  1.0))
				var dur := str(nd.get("duration", 0.5))
				_w(indent + "Call WN_AlphaFade(" + gid + ", " + opa + ", " + dur + ")")
			"togglegroup":
				var gid  := str(nd.get("group_id", 1))
				var mode := str(nd.get("toggle_mode", "Toggle On"))
				_w(indent + "Call WN_ToggleGroup(" + gid + ", \"" + mode + "\")")
			"colorchannel":
				var ch  := str(nd.get("channel", 1))
				var dur := str(nd.get("duration", 0.5))
				_w(indent + "Call WN_ColorChannel(" + ch + ", dur:=" + dur + ")")
			"pulseeffect":
				var gid := str(nd.get("group_id", 1))
				var fi  := str(nd.get("fade_in",  0.1))
				var hld := str(nd.get("hold",     0.2))
				var fo  := str(nd.get("fade_out", 0.1))
				_w(indent + "Call WN_PulseEffect(" + gid + ", " + fi + ", " + hld + ", " + fo + ")")
			"followtarget":
				var gid := str(nd.get("group_id",     1))
				var tgt := str(nd.get("target_group", 2))
				var spd := str(nd.get("x_speed",      100.0))
				_w(indent + "Call WN_FollowTarget(" + gid + ", " + tgt + ", " + spd + ")")
			"cameracontrol":
				var op  := str(nd.get("cam_op",  "Zoom"))
				var val := str(nd.get("value",   1.0))
				var dur := str(nd.get("duration", 0.5))
				_w(indent + "Call WN_CameraControl(\"" + op + "\", " + val + ", " + dur + ")")
			"trigger":
				var gid   := str(nd.get("group_id", 1))
				var delay := str(nd.get("delay",    0.0))
				_w(indent + "Call WN_Trigger(" + gid + ", " + delay + ")")
			# ── New trigger-style action nodes ─────────────────────────────
			"move":
				var prm := nd.get("params", {})
				var gid := str(prm.get("Group_ID", "1"))
				var mx  := str(prm.get("X",        "0"))
				var my  := str(prm.get("Y",        "0"))
				var dur := str(prm.get("Duration", "0.5"))
				_w(indent + "Call WN_Move(" + gid + ", " + mx + ", " + my + ", " + dur + ")")
			"rotate":
				var prm := nd.get("params", {})
				var gid := str(prm.get("Group_ID", "1"))
				var deg := str(prm.get("Degrees",  "90"))
				var dur := str(prm.get("Duration", "0.5"))
				_w(indent + "Call WN_Rotate(" + gid + ", " + deg + ", " + dur + ")")
			"scale":
				var prm := nd.get("params", {})
				var gid := str(prm.get("Group_ID", "1"))
				var sx  := str(prm.get("Scale_X",  "1"))
				var sy  := str(prm.get("Scale_Y",  "1"))
				var dur := str(prm.get("Duration", "0.5"))
				_w(indent + "Call WN_Scale(" + gid + ", " + sx + ", " + sy + ", " + dur + ")")
			"alpha":
				var prm := nd.get("params", {})
				var gid := str(prm.get("Group_ID", "1"))
				var opa := str(prm.get("Alpha",    "1.0"))
				var dur := str(prm.get("Duration", "0.5"))
				_w(indent + "Call WN_Alpha(" + gid + ", " + opa + ", " + dur + ")")
			"color trigger":
				var prm := nd.get("params", {})
				var ch  := str(prm.get("Channel",  "1"))
				var r   := str(prm.get("R",        "255"))
				var g   := str(prm.get("G",        "255"))
				var b   := str(prm.get("B",        "255"))
				var dur := str(prm.get("Duration", "0.5"))
				_w(indent + "Call WN_ColorTrigger(" + ch + ", " + r + ", " + g + ", " + b + ", " + dur + ")")
			"pulse":
				var prm := nd.get("params", {})
				var gid := str(prm.get("Group_ID", "1"))
				var r   := str(prm.get("R",        "255"))
				var g   := str(prm.get("G",        "100"))
				var b   := str(prm.get("B",        "100"))
				var fi  := str(prm.get("Fade_In",  "0.2"))
				var hld := str(prm.get("Hold",     "0.5"))
				var fo  := str(prm.get("Fade_Out", "0.2"))
				_w(indent + "Call WN_Pulse(" + gid + ", " + r + ", " + g + ", " + b + ", " + fi + ", " + hld + ", " + fo + ")")
			"spawn":
				var prm   := nd.get("params", {})
				var gid   := str(prm.get("Group_ID", "1"))
				var delay := str(prm.get("Delay",    "0"))
				_w(indent + "Call WN_Spawn(" + gid + ", " + delay + ")")
			"stop":
				var prm := nd.get("params", {})
				var gid := str(prm.get("Group_ID", "1"))
				_w(indent + "Call WN_Stop(" + gid + ")")
			"toggle":
				var prm := nd.get("params", {})
				var gid := str(prm.get("Group_ID", "1"))
				var act := str(prm.get("Active",   "1"))
				_w(indent + "Call WN_Toggle(" + gid + ", " + act + ")")
			"follow":
				var prm := nd.get("params", {})
				var gid := str(prm.get("Group_ID",     "1"))
				var tgt := str(prm.get("Target_Group", "2"))
				var xm  := str(prm.get("X_Mod",        "1"))
				var ym  := str(prm.get("Y_Mod",        "1"))
				var dur := str(prm.get("Duration",     "1.0"))
				_w(indent + "Call WN_Follow(" + gid + ", " + tgt + ", " + xm + ", " + ym + ", " + dur + ")")
			"shake":
				var prm  := nd.get("params", {})
				var str_ := str(prm.get("Strength", "1"))
				var intv := str(prm.get("Interval", "0.1"))
				var dur  := str(prm.get("Duration", "0.5"))
				_w(indent + "Call WN_Shake(" + str_ + ", " + intv + ", " + dur + ")")
			"play sfx":
				var prm := nd.get("params", {})
				var snd := str(prm.get("Sound",  ""))
				var vol := str(prm.get("Volume", "1"))
				var pit := str(prm.get("Pitch",  "1"))
				_w(indent + "Call WN_PlaySFX(\"" + snd + "\", " + vol + ", " + pit + ")")
			"animate":
				var prm := nd.get("params", {})
				var gid := str(prm.get("Group_ID",  "1"))
				var ani := str(prm.get("Animation", "0"))
				var spd := str(prm.get("Speed",     "1"))
				_w(indent + "Call WN_Animate(" + gid + ", " + ani + ", " + spd + ")")
			# ── New GD-equivalent nodes ───────────────────────────────────────────
			"counter":
				var prm := nd.get("params", {})
				var cname := str(prm.get("Name",  "score"))
				var op    := str(prm.get("Op",    "+="))
				var val   := str(prm.get("Value", "1"))
				match op:
					"+=": _w(indent + cname + " = " + cname + " + " + val)
					"-=": _w(indent + cname + " = " + cname + " - " + val)
					"*=": _w(indent + cname + " = " + cname + " * " + val)
					"/=": _w(indent + "If " + val + " <> 0 Then " + cname + " = " + cname + " / " + val)
					"%=": _w(indent + cname + " = " + cname + " Mod " + val)
					"=":  _w(indent + cname + " = " + val)
					_:    _w(indent + cname + " = " + cname + " + " + val + "  ' op=" + op)
			"random trig":
				var prm   := nd.get("params", {})
				var min_v := str(prm.get("Min",      "0"))
				var max_v := str(prm.get("Max",      "100"))
				var store := str(prm.get("Store_To", "result"))
				_w(indent + store + " = " + min_v + " + Rnd() * (" + max_v + " - " + min_v + ")")
			"branch":
				_emit_inline_branch(nd, indent)
			"cmp trig":
				_emit_inline_cmp_trig(nd, indent)
			"timer":
				var prm   := nd.get("params", {})
				var delay := str(prm.get("Delay",  "1.0"))
				var rep   := str(prm.get("Repeat", "0"))
				_w(indent + "Call WN_Timer(" + delay + ", " + rep + ")")
			"sequence":
				_emit_inline_sequence(nd, indent)
			"zoom":
				var prm := nd.get("params", {})
				var z   := str(prm.get("Zoom",     "1.0"))
				var dur := str(prm.get("Duration", "0.5"))
				_w(indent + "Call WN_Zoom(" + z + ", " + dur + ")")
			"camera move":
				var prm := nd.get("params", {})
				var tgt := str(prm.get("Target_Group", "1"))
				var dur := str(prm.get("Duration",     "1.0"))
				var ox  := str(prm.get("X_Offset",     "0"))
				var oy  := str(prm.get("Y_Offset",     "0"))
				_w(indent + "Call WN_CameraMove(" + tgt + ", " + dur + ", " + ox + ", " + oy + ")")
			"get prop":
				var prm   := nd.get("params", {})
				var path  := str(prm.get("Node_Path", "Player"))
				var prop  := str(prm.get("Property",  "position.x"))
				var store := str(prm.get("Store_To",  "result"))
				_w(indent + store + " = GetNode(\"" + path + "\")." + prop)
			"set prop":
				var prm  := nd.get("params", {})
				var path := str(prm.get("Node_Path", "Player"))
				var prop := str(prm.get("Property",  "position.x"))
				var val  := str(prm.get("Value",     "0"))
				_w(indent + "GetNode(\"" + path + "\")." + prop + " = " + val)
			"input poll":
				_emit_inline_input_poll(nd, indent)
			"expr":
				var prm   := nd.get("params", {})
				var store := str(prm.get("Store_To",   "result"))
				var xpr   := str(prm.get("Expression", "0"))
				_w(indent + store + " = " + xpr)
			"delta var":
				_emit_inline_delta_var(nd, indent)
			_:
				# Generic fallback
				var safe := working_nodes_codegen.sanitize_name(str(nd.get("title", n_name)), "WNAction")
				_w(indent + "Call " + safe + "()  ' kind=" + kind)

	# ─── Action sub (implementation body) ────────────────────────────────────

	func _emit_action_sub(nd: Dictionary) -> void:
		var kind   := str(nd.get("_kind", "")).to_lower()
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))

		match kind:
			"action":
				var act_type := str(nd.get("action_type", nd.get("title", "Print"))).to_lower()
				_w("Sub Action_" + n_name + "()  ' " + title)
				_w("    Dim target As String")
				_w("    target = \"\" ' Set to target node path")
				if "move" in act_type:
					_w("    ' Move target node")
					_w("    ' GetNode(target).position.x += 10")
					_w("    Print \"Action_" + n_name + ": Move\"")
				elif "rotat" in act_type:
					_w("    ' Rotate target node")
					_w("    Print \"Action_" + n_name + ": Rotate\"")
				elif "scale" in act_type:
					_w("    ' Scale target node")
					_w("    Print \"Action_" + n_name + ": Scale\"")
				elif "anim" in act_type or "play" in act_type:
					_w("    ' Play animation or sound")
					_w("    Print \"Action_" + n_name + ": Play\"")
				elif "print" in act_type or "log" in act_type:
					_w("    Print \"Action_" + n_name + " executed\"")
				elif "tween" in act_type:
					_w("    ' Tween target node property")
					_w("    Print \"Action_" + n_name + ": Tween\"")
				elif "wait" in act_type:
					_w("    ' Wait / yield")
					_w("    Print \"Action_" + n_name + ": Wait\"")
				elif "set" in act_type:
					_w("    ' Set property on target")
					_w("    Print \"Action_" + n_name + ": SetProperty\"")
				elif "emit" in act_type:
					_w("    ' Emit a signal")
					_w("    Print \"Action_" + n_name + ": EmitSignal\"")
				elif "call" in act_type:
					_w("    ' Call method on target")
					_w("    Print \"Action_" + n_name + ": CallMethod\"")
				else:
					_w("    Print \"Action_" + n_name + ": " + title + "\"")
				_w("End Sub")
				_w("")

			"movegroup":
				# Handled inline — no separate sub needed
				pass

			"trigger":
				# Handled inline — no separate sub needed
				pass

			_:
				# Handled inline — no separate sub needed
				pass

	# ─── Condition sub ────────────────────────────────────────────────────────

	func _emit_condition_sub(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var kind   := str(nd.get("_kind", "")).to_lower()

		if kind == "switch":
			_w("Function WN_Switch_" + n_name + "(ByVal condition As Boolean, ByVal true_val As Variant, ByVal false_val As Variant) As Variant")
			_w("    If condition Then")
			_w("        WN_Switch_" + n_name + " = true_val")
			_w("    Else")
			_w("        WN_Switch_" + n_name + " = false_val")
			_w("    End If")
			_w("End Function  ' Switch: " + title)
			_w("")
		else:
			var cmp_op  := str(nd.get("compare_op", "=="))
			var cmp_val := str(nd.get("compare_value", "0"))
			_w("Function WN_Cond_" + n_name + "(ByVal value As Variant) As Boolean")
			_w("    WN_Cond_" + n_name + " = (value " + cmp_op + " " + cmp_val + ")")
			_w("End Function  ' Condition: " + title)
			_w("")

	# ─── Loop sub ────────────────────────────────────────────────────────────

	func _emit_loop_sub(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var count  := int(nd.get("loop_count", 3))
		_w("Sub WN_Loop_" + n_name + "()")
		_w("    ' Loop: " + title)
		_w("    Dim i As Long")
		_w("    For i = 0 To " + str(count - 1) + " Step 1")
		_w("        ' TODO: body")
		_w("    Next i")
		_w("End Sub")
		_w("")

	# ─── Function node ────────────────────────────────────────────────────────

	func _emit_function_node(nd: Dictionary) -> void:
		var fn_name := working_nodes_codegen.sanitize_name(
			str(nd.get("fn_name", nd.get("title", "my_function"))), "WNFunction"
		)
		var ret_type := _map_type(str(nd.get("return_type", "void")))
		var title := str(nd.get("title", fn_name))

		if ret_type == "Variant" or str(nd.get("return_type", "void")).to_lower() == "void":
			_w("Sub " + fn_name + "(ByVal param_a As Double, ByVal param_b As Double)")
			_w("    ' Function node: " + title)
			_w("    ' TODO: implement body")
			_w("End Sub")
		else:
			_w("Function " + fn_name + "(ByVal param_a As Double, ByVal param_b As Double) As " + ret_type)
			_w("    ' Function node: " + title)
			_w("    " + fn_name + " = param_a  ' TODO: implement")
			_w("End Function")
		_w("")

	# ─── Math functions ───────────────────────────────────────────────────────

	func _emit_math_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var op     := str(nd.get("math_op", nd.get("title", "Add"))).to_lower()
		_w("Function WN_Math_" + n_name + "(ByVal a As Double, ByVal b As Double) As Double")
		_w("    ' Math node: " + title)
		match op:
			"add":            _w("    WN_Math_" + n_name + " = a + b")
			"subtract":       _w("    WN_Math_" + n_name + " = a - b")
			"multiply":       _w("    WN_Math_" + n_name + " = a * b")
			"divide":         _w("    If b <> 0 Then WN_Math_" + n_name + " = a / b Else WN_Math_" + n_name + " = 0")
			"multiply add":   _w("    WN_Math_" + n_name + " = a * b + 0  ' MultiplyAdd (c not wired)")
			"power":          _w("    WN_Math_" + n_name + " = a ^ b")
			"log":            _w("    WN_Math_" + n_name + " = Log(a)")
			"sqrt":           _w("    WN_Math_" + n_name + " = Sqr(a)")
			"absolute":       _w("    WN_Math_" + n_name + " = Abs(a)")
			"min":            _w("    If a < b Then WN_Math_" + n_name + " = a Else WN_Math_" + n_name + " = b")
			"max":            _w("    If a > b Then WN_Math_" + n_name + " = a Else WN_Math_" + n_name + " = b")
			"floor":          _w("    WN_Math_" + n_name + " = Int(a)")
			"ceil":           _w("    If a = Int(a) Then WN_Math_" + n_name + " = a Else WN_Math_" + n_name + " = Int(a) + 1")
			"round":          _w("    WN_Math_" + n_name + " = CLng(a)")
			"modulo":         _w("    WN_Math_" + n_name + " = a Mod b")
			"sin":            _w("    WN_Math_" + n_name + " = Sin(a)")
			"cos":            _w("    WN_Math_" + n_name + " = Cos(a)")
			"tan":            _w("    WN_Math_" + n_name + " = Tan(a)")
			"arctan":         _w("    WN_Math_" + n_name + " = Atn(a)")
			"arctan2":        _w("    WN_Math_" + n_name + " = Atn(a / b)")
			"lerp":           _w("    WN_Math_" + n_name + " = a + (b - a) * 0.5  ' t not wired")
			"clamp":          _w("    If a < 0 Then WN_Math_" + n_name + " = 0 ElseIf a > 1 Then WN_Math_" + n_name + " = 1 Else WN_Math_" + n_name + " = a")
			_:                _w("    WN_Math_" + n_name + " = a + b  ' op=" + op)
		_w("End Function")
		_w("")

	func _emit_boolmath_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var op     := str(nd.get("bool_op", "AND")).to_upper()
		_w("Function WN_BoolMath_" + n_name + "(ByVal a As Boolean, ByVal b As Boolean) As Boolean")
		_w("    ' BoolMath node: " + title)
		match op:
			"AND":  _w("    WN_BoolMath_" + n_name + " = a And b")
			"OR":   _w("    WN_BoolMath_" + n_name + " = a Or b")
			"NOT":  _w("    WN_BoolMath_" + n_name + " = Not a")
			"NAND": _w("    WN_BoolMath_" + n_name + " = Not (a And b)")
			"NOR":  _w("    WN_BoolMath_" + n_name + " = Not (a Or b)")
			"XOR":  _w("    WN_BoolMath_" + n_name + " = a Xor b")
			"XNOR": _w("    WN_BoolMath_" + n_name + " = Not (a Xor b)")
			_:      _w("    WN_BoolMath_" + n_name + " = a And b")
		_w("End Function")
		_w("")

	func _emit_vectormath_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		_w("' VectorMath node: " + title)
		_w("' (Vector operations use x/y/z components — expand as needed)")
		_w("Function WN_VecMath_" + n_name + "_X(ByVal ax As Double, ByVal ay As Double, ByVal bx As Double, ByVal by As Double) As Double")
		_w("    WN_VecMath_" + n_name + "_X = ax + bx  ' TODO: set correct vector op")
		_w("End Function")
		_w("Function WN_VecMath_" + n_name + "_Y(ByVal ax As Double, ByVal ay As Double, ByVal bx As Double, ByVal by As Double) As Double")
		_w("    WN_VecMath_" + n_name + "_Y = ay + by")
		_w("End Function")
		_w("")

	func _emit_maprange_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		_w("Function WN_MapRange_" + n_name + "(ByVal value As Double, ByVal from_min As Double, ByVal from_max As Double, ByVal to_min As Double, ByVal to_max As Double) As Double")
		_w("    ' MapRange node: " + title)
		_w("    If from_max = from_min Then")
		_w("        WN_MapRange_" + n_name + " = to_min")
		_w("    Else")
		_w("        WN_MapRange_" + n_name + " = to_min + (value - from_min) / (from_max - from_min) * (to_max - to_min)")
		_w("    End If")
		_w("End Function")
		_w("")

	func _emit_randomvalue_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		_w("Function WN_Random_" + n_name + "(ByVal min_val As Double, ByVal max_val As Double) As Double")
		_w("    ' RandomValue node: " + title)
		_w("    WN_Random_" + n_name + " = min_val + Rnd() * (max_val - min_val)")
		_w("End Function")
		_w("")

	func _emit_compare_function(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var op     := str(nd.get("compare_op", "< Less Than")).to_lower()
		_w("Function WN_Compare_" + n_name + "(ByVal a As Double, ByVal b As Double) As Boolean")
		_w("    ' Compare node: " + title)
		if "less than" in op or op == "<":
			_w("    WN_Compare_" + n_name + " = (a < b)")
		elif "greater than" in op or op == ">":
			_w("    WN_Compare_" + n_name + " = (a > b)")
		elif "lte" in op or op == "<=":
			_w("    WN_Compare_" + n_name + " = (a <= b)")
		elif "gte" in op or op == ">=":
			_w("    WN_Compare_" + n_name + " = (a >= b)")
		elif "not" in op or op == "!=":
			_w("    WN_Compare_" + n_name + " = (a <> b)")
		else:
			_w("    WN_Compare_" + n_name + " = (a = b)")
		_w("End Function")
		_w("")


# ─── Scene Generator ─────────────────────────────────────────────────────────

class _SceneGen:

	func build_2d(data: Dictionary, vg_script_path: String, root_type: String = "Node2D") -> String:
		return _build_scene(data, vg_script_path, false, root_type)

	func build_3d(data: Dictionary, vg_script_path: String, root_type: String = "Node3D") -> String:
		return _build_scene(data, vg_script_path, true, root_type)

	func _build_scene(data: Dictionary, vg_script_path: String, is_3d: bool, override_root: String = "") -> String:
		var root_type  := override_root if not override_root.is_empty() else ("Node3D" if is_3d else "Node2D")
		var child_type := "Node3D" if is_3d else "Node2D"
		var sprite_type := "MeshInstance3D" if is_3d else "Sprite2D"

		var lines: PackedStringArray = PackedStringArray()
		var w := func(s: String): lines.append(s)

		# ── Header ────────────────────────────────────────────────────────
		w.call("[gd_scene load_steps=2 format=3 uid=\"uid://wn_generated\"]")
		w.call("")
		if not vg_script_path.is_empty():
			w.call("[ext_resource type=\"Script\" path=\"" + vg_script_path + "\" id=\"1_script\"]")
			w.call("")

		# ── Collect groups and action nodes ───────────────────────────────
		var groups: Dictionary = {}
		for g in data.get("groups", []):
			groups[int(g.get("id", 0))] = g

		var nodes_list: Array = data.get("nodes", [])
		var action_kinds := [
			"action", "movegroup", "rotategroup", "trigger", "followtarget",
			"spawntrigger", "alphafade", "togglegroup",
		]

		# ── Root node ─────────────────────────────────────────────────────
		var scene_name := "WNScene"
		w.call("[node name=\"" + scene_name + "\" type=\"" + root_type + "\"]")
		if not vg_script_path.is_empty():
			w.call("script = ExtResource(\"1_script\")")
		w.call("")

		# ── Group containers ──────────────────────────────────────────────
		var emitted_groups: Dictionary = {}
		for nd in nodes_list:
			var n_kind := str(nd.get("kind", nd.get("type", "action"))).to_lower()
			if n_kind in action_kinds or n_kind == "event" or n_kind == "timedevent":
				var gid := int(nd.get("group", nd.get("wn_group", 1)))
				if gid > 0 and not emitted_groups.has(gid):
					emitted_groups[gid] = true
					var g_info: Dictionary = groups.get(gid, {})
					var g_name := working_nodes_codegen.sanitize_name(
						str(g_info.get("name", "Group%d" % gid)), "Group%d" % gid
					)
					w.call("[node name=\"" + g_name + "\" type=\"" + child_type + "\" parent=\".\"]")
					w.call("")

		# ── Per-node scene objects ────────────────────────────────────────
		for nd in nodes_list:
			var n_kind := str(nd.get("kind", nd.get("type", "action"))).to_lower()
			if not (n_kind in action_kinds):
				continue

			var n_name  := str(nd.get("name", nd.get("title", "WN_0")))
			var title   := str(nd.get("title", n_name))
			var obj_name := working_nodes_codegen.sanitize_name(title, "WNObj")
			var gid      := int(nd.get("group", nd.get("wn_group", 1)))
			var g_info: Dictionary = groups.get(gid, {})
			var g_parent := working_nodes_codegen.sanitize_name(
				str(g_info.get("name", "Group%d" % gid)), "Group%d" % gid
			)
			var parent_path := g_parent if emitted_groups.has(gid) else "."

			# Choose node type based on action kind
			var obj_type := sprite_type
			match n_kind:
				"movegroup", "rotategroup", "followtarget":
					obj_type = child_type
				"alphafade", "colorchannel", "pulseeffect":
					obj_type = sprite_type
				_:
					obj_type = child_type

			w.call("[node name=\"" + obj_name + "\" type=\"" + obj_type + "\" parent=\"" + parent_path + "\"]")

			# Position from graph node's canvas position
			var pos_arr: Array = nd.get("position", [0, 0])
			var px: float = float(pos_arr[0] if pos_arr.size() > 0 else 0) * 0.25
			var py: float = float(pos_arr[1] if pos_arr.size() > 1 else 0) * 0.25

			if is_3d:
				w.call("transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, " + "%.3f" % px + ", " + "%.3f" % py + ", 0)")
			else:
				w.call("position = Vector2(" + "%.1f" % px + ", " + "%.1f" % py + ")")
			w.call("")

		return "\n".join(Array(lines))


# ─── GDScript Generator ───────────────────────────────────────────────────────

class _GDScriptGen:
	var _nodes: Dictionary = {}
	var _conns: Array = []
	var _lines: PackedStringArray = PackedStringArray()

	func build(data: Dictionary) -> String:
		_nodes = {}
		_conns = data.get("connections", [])
		_lines = PackedStringArray()
		for nd in data.get("nodes", []):
			var n_name: String = str(nd.get("name", nd.get("title", "WN_0")))
			var n_kind: String = str(nd.get("kind", nd.get("type", "action"))).capitalize()
			var entry: Dictionary = nd.duplicate()
			entry["_kind"] = n_kind
			entry["_name"] = n_name
			_nodes[n_name] = entry

		_w("# Generated by Working Nodes — VisualGasic")
		_w("# Edit the graph in Working Nodes to regenerate, or edit here directly.")
		_w("# To run: attach this script to a Node in the scene.")
		_w("")
		_w("extends Node")
		_w("")

		# Variables
		var var_nodes := _nodes_of_kind("Variable")
		if not var_nodes.is_empty():
			_w("# --- Variables ---")
			for nd in var_nodes:
				var vname := working_nodes_codegen.sanitize_name(
					str(nd.get("var_name", nd.get("title", "my_var"))), "my_var")
				var vtype := _gd_type(str(nd.get("var_type", "float")))
				_w("var %s: %s" % [vname, vtype])
			_w("")

		# Event → func mappings
		var event_kinds := ["Event", "Timedevent", "Collisiontrigger"]
		var event_nodes: Array = []
		for k in event_kinds:
			event_nodes.append_array(_nodes_of_kind(k))

		if event_nodes.is_empty():
			_w("func _ready() -> void:")
			_w("\t# No Event nodes — all actions called here")
			for nd in _nodes_of_kind("Action"):
				var an := str(nd.get("_name", ""))
				_w("\t_%s()" % an.to_lower())
			if _nodes_of_kind("Action").is_empty():
				_w("\tpass")
		else:
			for nd in event_nodes:
				_emit_event_func(nd)

		# Per-action funcs
		for nd in _nodes_of_kind("Action"):
			_emit_action_func(nd)

		# Math funcs
		for nd in _nodes_of_kind("Math"):
			_emit_math_func(nd)
		for nd in _nodes_of_kind("Boolmath"):
			_emit_boolmath_func(nd)

		# Function nodes
		for nd in _nodes_of_kind("Function"):
			_emit_function_node(nd)

		return "\n".join(Array(_lines))

	func _w(line: String) -> void:
		_lines.append(line)

	func _nodes_of_kind(kind: String) -> Array:
		var out: Array = []
		var lk := kind.to_lower()
		for n in _nodes.values():
			if str(n.get("_kind", "")).to_lower() == lk:
				out.append(n)
		return out

	func _gd_type(t: String) -> String:
		match t.to_lower():
			"float", "double": return "float"
			"int", "integer", "long": return "int"
			"bool", "boolean": return "bool"
			"string": return "String"
			"vector2": return "Vector2"
			"vector3": return "Vector3"
			"color": return "Color"
			_: return "Variant"

	func _exec_chain(start_name: String) -> Array:
		var ordered: Array = []
		var visited: Dictionary = {}
		var queue: Array = [start_name]
		while not queue.is_empty():
			var cur: String = queue.pop_front()
			if visited.has(cur): continue
			visited[cur] = true
			if _nodes.has(cur): ordered.append(_nodes[cur])
			for c in _conns:
				if str(c.get("from", "")) == cur:
					queue.push_back(str(c.get("to", "")))
		return ordered

	func _event_func_name(ev_type: String, n_name: String) -> String:
		var t := ev_type.to_lower()
		if "start" in t or "ready" in t or "load" in t: return "_ready"
		elif "process" in t or "update" in t or "frame" in t: return "_process"
		elif "input" in t or "click" in t or "touch" in t: return "_input"
		elif "timer" in t: return "_on_timer_timeout"
		elif "collision" in t: return "_on_body_entered"
		else:
			return "_on_" + working_nodes_codegen.sanitize_name(ev_type, "event_" + n_name).to_lower()

	func _emit_event_func(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var ev_type := str(nd.get("event_type", nd.get("title", "On Ready")))
		var fn_name := _event_func_name(ev_type, n_name)
		var args := ""
		if fn_name == "_process": args = "delta: float"
		elif fn_name == "_input": args = "event: InputEvent"
		elif fn_name == "_on_body_entered": args = "body: Node"
		_w("")
		_w("func %s(%s) -> void:" % [fn_name, args])
		if nd.get("_breakpoint", false):
			_w("\tprint(\">>> BREAKPOINT: %s\")" % str(nd.get("title", n_name)))
		var chain := _exec_chain(n_name)
		var had_body := false
		for linked in chain:
			if str(linked.get("_name", "")) == n_name: continue
			var kind := str(linked.get("_kind", "")).to_lower()
			match kind:
				"action":
					_w("\t_%s()" % str(linked.get("_name", "")).to_lower())
					had_body = true
				"variable": pass
				_:
					_w("\tpass  # %s: %s" % [kind, str(linked.get("title", ""))])
					had_body = true
		if not had_body:
			_w("\tpass")

	func _emit_action_func(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var act    := str(nd.get("action_type", nd.get("title", "print"))).to_lower()
		_w("")
		_w("func _%s() -> void:  # %s" % [n_name.to_lower(), title])
		if nd.get("_breakpoint", false):
			_w("\tprint(\">>> BREAKPOINT: %s\")" % title)
		if "move" in act:          _w("\tposition.x += 10.0")
		elif "rotat" in act:       _w("\trotation_degrees += 10.0")
		elif "scale" in act:       _w("\tscale *= 1.1")
		elif "print" in act or "log" in act: _w("\tprint(\"%s\")" % title)
		elif "anim" in act:        _w("\t# $AnimationPlayer.play(\"animation_name\")")
		elif "tween" in act:
			_w("\tvar tween := create_tween()")
			_w("\ttween.tween_property(self, \"position\", Vector2.ZERO, 0.5)")
		elif "wait" in act:        _w("\tawait get_tree().create_timer(1.0).timeout")
		elif "emit" in act:        _w("\t# emit_signal(\"signal_name\")")
		elif "call" in act:        _w("\t# call(\"method_name\")")
		elif "set" in act:         _w("\t# set(\"property_name\", value)")
		else:                      _w("\tprint(\"%s executed\")" % title)

	func _emit_math_func(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var op     := str(nd.get("math_op", nd.get("title", "add"))).to_lower()
		_w("")
		_w("func _wn_math_%s(a: float, b: float) -> float:  # %s" % [n_name.to_lower(), title])
		match op:
			"add":        _w("\treturn a + b")
			"subtract":   _w("\treturn a - b")
			"multiply":   _w("\treturn a * b")
			"divide":     _w("\treturn a / b if b != 0.0 else 0.0")
			"power":      _w("\treturn pow(a, b)")
			"sqrt":       _w("\treturn sqrt(a)")
			"absolute":   _w("\treturn abs(a)")
			"min":        _w("\treturn minf(a, b)")
			"max":        _w("\treturn maxf(a, b)")
			"floor":      _w("\treturn floor(a)")
			"ceil":       _w("\treturn ceil(a)")
			"round":      _w("\treturn round(a)")
			"sin":        _w("\treturn sin(a)")
			"cos":        _w("\treturn cos(a)")
			"tan":        _w("\treturn tan(a)")
			"lerp":       _w("\treturn lerp(a, b, 0.5)  # t not wired")
			"clamp":      _w("\treturn clamp(a, 0.0, 1.0)")
			_:            _w("\treturn a + b  # op=%s" % op)

	func _emit_boolmath_func(nd: Dictionary) -> void:
		var n_name := str(nd.get("_name", "WN_0"))
		var title  := str(nd.get("title", n_name))
		var op     := str(nd.get("bool_op", "AND")).to_upper()
		_w("")
		_w("func _wn_bool_%s(a: bool, b: bool) -> bool:  # %s" % [n_name.to_lower(), title])
		match op:
			"AND":  _w("\treturn a and b")
			"OR":   _w("\treturn a or b")
			"NOT":  _w("\treturn not a")
			"NAND": _w("\treturn not (a and b)")
			"NOR":  _w("\treturn not (a or b)")
			"XOR":  _w("\treturn a != b")
			"XNOR": _w("\treturn a == b")
			_:      _w("\treturn a and b")

	func _emit_function_node(nd: Dictionary) -> void:
		var fn_name := working_nodes_codegen.sanitize_name(
			str(nd.get("fn_name", nd.get("title", "my_function"))), "wn_function")
		var ret := str(nd.get("return_type", "void")).to_lower()
		var gd_ret := "void" if ret in ["void", ""] else _gd_type(ret)
		_w("")
		_w("func %s(param_a: float, param_b: float) -> %s:" % [fn_name, gd_ret])
		if gd_ret == "void":
			_w("\tpass  # TODO: implement")
		else:
			_w("\treturn param_a  # TODO: implement")


# ─── VG Parser (round-trip import) ───────────────────────────────────────────
# Parses the top-level Sub/Function/Dim statements in a .vg file and creates
# a minimal Working Nodes graph dictionary that the editor can load.

class _VGParser:

	func parse(vg_code: String) -> Dictionary:
		var lines := vg_code.split("\n")
		var nodes: Array = []
		var connections: Array = []
		var node_id := 1

		var event_entries: Array = []  # {title, sub_line}
		var action_entries: Array = [] # {title, sub_line}
		var fn_entries: Array = []     # {title, sub_line}

		for raw_line in lines:
			var line := raw_line.strip_edges()
			if line.is_empty() or line.begins_with("'"):
				continue
			var tl := line.to_lower()

			# Variable: Dim name As Type
			if tl.begins_with("dim "):
				var parts := line.split(" ", false)
				if parts.size() >= 4:
					nodes.append({
						"name": "WN_Var_%d" % node_id,
						"title": parts[1],
						"kind": "Variable", "type": "variable",
						"var_name": parts[1], "var_type": parts[3],
						"position": [60, 60 + node_id * 90],
					})
					node_id += 1
				continue

			# Sub / End Sub
			if tl.begins_with("sub "):
				var sub_name := _extract_sub_name(line)
				var ev_type := _classify_event(sub_name)
				if ev_type != "":
					event_entries.append({"title": sub_name, "event_type": ev_type})
				else:
					action_entries.append({"title": sub_name})
				continue

			# Function
			if tl.begins_with("function "):
				var fn_name := _extract_sub_name(line)
				fn_entries.append({"title": fn_name})
				continue

		# Emit event nodes
		var x := 120
		var prev_name := ""
		for i in event_entries.size():
			var e: Dictionary = event_entries[i]
			var en := "WN_Ev_%d" % node_id
			nodes.append({
				"name": en, "title": e.title,
				"kind": "Event", "type": "event",
				"event_type": e.get("event_type", "On Start"),
				"position": [x + i * 340, 120],
			})
			node_id += 1
			if i == 0: prev_name = en

		# Emit action nodes and chain them from first event
		for i in action_entries.size():
			var a: Dictionary = action_entries[i]
			var an := "WN_Act_%d" % node_id
			nodes.append({
				"name": an, "title": a.title,
				"kind": "Action", "type": "action",
				"position": [x + i * 240, 320],
			})
			if not prev_name.is_empty():
				connections.append({
					"from": prev_name, "from_port": 0,
					"to": an, "to_port": 0,
				})
				prev_name = an
			node_id += 1

		# Emit function nodes
		for i in fn_entries.size():
			var f: Dictionary = fn_entries[i]
			var fn := "WN_Fn_%d" % node_id
			nodes.append({
				"name": fn, "title": f.title,
				"kind": "Function", "type": "function",
				"fn_name": f.title,
				"position": [x + i * 240, 500],
			})
			node_id += 1

		if nodes.is_empty() and connections.is_empty():
			# Fallback: create a single Event + Action node
			nodes.append({"name":"WN_Ev_1","title":"Form_Load","kind":"Event","type":"event","event_type":"On Start","position":[120,120]})
			nodes.append({"name":"WN_Act_2","title":"Imported Action","kind":"Action","type":"action","position":[400,200]})
			connections.append({"from":"WN_Ev_1","from_port":0,"to":"WN_Act_2","to_port":0})

		return {
			"version": 1,
			"next_node_id": node_id,
			"next_group_id": 2,
			"nodes": nodes,
			"connections": connections,
			"groups": [{"id": 1, "name": "Group 1", "color": "#88AAFF"}],
		}

	func _extract_sub_name(line: String) -> String:
		var after_kw := line.split(" ", false)
		var raw := after_kw[1] if after_kw.size() > 1 else "Unknown"
		return raw.split("(")[0]

	func _classify_event(sub_name: String) -> String:
		var tl := sub_name.to_lower()
		if "form_load" in tl or "form_ready" in tl: return "On Start"
		elif "form_timer" in tl or "timer" in tl: return "On Timer"
		elif "form_click" in tl or "click" in tl: return "On Click"
		elif "form_signal" in tl or "signal" in tl: return "On Signal"
		elif "form_collision" in tl or "collision" in tl: return "On Collision"
		elif "form_" in tl: return "On Start"
		return ""  # Not an event sub
