#!/usr/bin/env python3
"""Compare generated bytecode dump output against the committed baseline."""
from __future__ import annotations

import argparse
import json
import sys
from difflib import unified_diff
from pathlib import Path


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "baseline",
        nargs="?",
        default="tests/bytecode_baseline.json",
        help="Path to the expected baseline JSON file",
    )
    parser.add_argument(
        "candidate",
        nargs="?",
        default="bytecode_dump.json",
        help="Path to the newly generated JSON file",
    )
    parser.add_argument(
        "--diff-output",
        dest="diff_output",
        help="Optional file to store the textual diff for later inspection",
    )
    parser.add_argument(
        "--max-lines",
        dest="max_lines",
        type=int,
        default=200,
        help="Maximum number of diff lines to emit (default: 200)",
    )
    return parser.parse_args()


def _load_json(path: Path) -> object:
    if not path.exists():
        print(f"Missing file: {path}", file=sys.stderr)
        return None
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except json.JSONDecodeError as exc:
        print(f"Failed to parse JSON from {path}: {exc}", file=sys.stderr)
        return None


def _normalized_dump(payload: object) -> list[str]:
    return json.dumps(payload, indent=2, sort_keys=True).splitlines(keepends=True)


def _write_diff(diff_lines: list[str], destination: Path) -> None:
    if not destination:
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8") as handle:
        handle.writelines(diff_lines)


def main() -> int:
    args = _parse_args()
    baseline_arg = Path(args.baseline)
    candidate_arg = Path(args.candidate)
    diff_output = Path(args.diff_output) if args.diff_output else None

    baseline = _load_json(baseline_arg)
    candidate = _load_json(candidate_arg)
    if baseline is None or candidate is None:
        return 2

    if baseline == candidate:
        print("✅ Bytecode dump matches baseline")
        if diff_output and diff_output.exists():
            diff_output.unlink()
        return 0

    print("❌ Bytecode dump differs from baseline", file=sys.stderr)
    baseline_lines = _normalized_dump(baseline)
    candidate_lines = _normalized_dump(candidate)
    diff_iter = unified_diff(
        baseline_lines,
        candidate_lines,
        fromfile=str(baseline_arg),
        tofile=str(candidate_arg),
        n=3,
    )
    emitted = 0
    collected: list[str] = []
    max_lines = max(1, args.max_lines)
    for line in diff_iter:
        sys.stderr.write(line)
        collected.append(line)
        emitted += 1
        if emitted >= max_lines:
            trunc = "\n...diff truncated...\n"
            sys.stderr.write(trunc)
            collected.append(trunc)
            break
    if diff_output:
        _write_diff(collected, diff_output)
    return 1


if __name__ == "__main__":
    sys.exit(main())
