// VGSettings — VB6-style GetSetting/SaveSetting with INI file storage

#include "visual_gasic_settings.h"
#include <godot_cpp/variant/utility_functions.hpp>
#include <godot_cpp/classes/file_access.hpp>
#include <godot_cpp/classes/dir_access.hpp>
#include <godot_cpp/classes/os.hpp>
#include <godot_cpp/classes/project_settings.hpp>

using namespace godot;

// Static member initialization
Dictionary *VGSettings::settings_cache = nullptr;
bool VGSettings::cache_dirty = false;

Dictionary &VGSettings::get_cache() {
    if (!settings_cache) {
        settings_cache = memnew(Dictionary);
    }
    return *settings_cache;
}

void VGSettings::_bind_methods() {
    ClassDB::bind_static_method("VGSettings", D_METHOD("save_setting", "app_name", "section", "key", "value"),
                                &VGSettings::save_setting);
    ClassDB::bind_static_method("VGSettings", D_METHOD("get_setting", "app_name", "section", "key", "default"),
                                &VGSettings::get_setting, DEFVAL(""));
    ClassDB::bind_static_method("VGSettings", D_METHOD("delete_setting", "app_name", "section", "key"),
                                &VGSettings::delete_setting, DEFVAL(""), DEFVAL(""));
    ClassDB::bind_static_method("VGSettings", D_METHOD("get_all_settings", "app_name", "section"),
                                &VGSettings::get_all_settings);
    ClassDB::bind_static_method("VGSettings", D_METHOD("get_section", "app_name", "section"),
                                &VGSettings::get_section);
    ClassDB::bind_static_method("VGSettings", D_METHOD("get_sections", "app_name"),
                                &VGSettings::get_sections);
    ClassDB::bind_static_method("VGSettings", D_METHOD("has_setting", "app_name", "section", "key"),
                                &VGSettings::has_setting);
    ClassDB::bind_static_method("VGSettings", D_METHOD("flush"), &VGSettings::flush);
}

VGSettings::VGSettings() {}
VGSettings::~VGSettings() {}

String VGSettings::get_settings_dir() {
    // Store settings in user://settings/
    return "user://settings";
}

String VGSettings::get_ini_path(const String &p_app_name) {
    return get_settings_dir() + String("/") + p_app_name + String(".ini");
}

Dictionary VGSettings::parse_ini_file(const String &p_path) {
    Dictionary result;

    String abs_path = ProjectSettings::get_singleton()->globalize_path(p_path);
    if (!FileAccess::file_exists(p_path)) return result;

    Ref<FileAccess> f = FileAccess::open(p_path, FileAccess::READ);
    if (!f.is_valid()) return result;

    String current_section;
    while (!f->eof_reached()) {
        String line = f->get_line().strip_edges();

        // Skip comments and empty lines
        if (line.is_empty() || line.begins_with(";") || line.begins_with("#")) continue;

        // Section header: [SectionName]
        if (line.begins_with("[") && line.ends_with("]")) {
            current_section = line.substr(1, line.length() - 2);
            if (!result.has(current_section)) {
                result[current_section] = Dictionary();
            }
            continue;
        }

        // Key=Value
        int eq_pos = line.find("=");
        if (eq_pos > 0 && !current_section.is_empty()) {
            String key = line.substr(0, eq_pos).strip_edges();
            String value = line.substr(eq_pos + 1).strip_edges();
            Dictionary section = result[current_section];
            section[key] = value;
            result[current_section] = section;
        }
    }

    return result;
}

void VGSettings::write_ini_file(const String &p_path, const Dictionary &p_data) {
    // Ensure directory exists
    String dir = get_settings_dir();
    if (!DirAccess::dir_exists_absolute(dir)) {
        Ref<DirAccess> d = DirAccess::open("user://");
        if (d.is_valid()) {
            d->make_dir("settings");
        }
    }

    Ref<FileAccess> f = FileAccess::open(p_path, FileAccess::WRITE);
    if (!f.is_valid()) {
        UtilityFunctions::printerr("[VGSettings] Failed to write: ", p_path);
        return;
    }

    // Write header comment
    f->store_line("; VisualGasic Settings File");
    f->store_line("; Auto-generated by SaveSetting()");
    f->store_line("");

    Array sections = p_data.keys();
    for (int i = 0; i < sections.size(); i++) {
        String section_name = sections[i];
        Dictionary section = p_data[section_name];

        f->store_line("[" + section_name + "]");

        Array keys = section.keys();
        for (int j = 0; j < keys.size(); j++) {
            String key = keys[j];
            String value = section[key];
            f->store_line(key + "=" + value);
        }
        f->store_line("");
    }
}

void VGSettings::ensure_loaded(const String &p_app_name) {
    if (get_cache().has(p_app_name)) return;

    String ini_path = get_ini_path(p_app_name);
    Dictionary data = parse_ini_file(ini_path);
    get_cache()[p_app_name] = data;
}

void VGSettings::flush_to_disk(const String &p_app_name) {
    if (!get_cache().has(p_app_name)) return;
    String ini_path = get_ini_path(p_app_name);
    write_ini_file(ini_path, get_cache()[p_app_name]);
}

void VGSettings::save_setting(const String &p_app_name, const String &p_section,
                               const String &p_key, const String &p_value) {
    ensure_loaded(p_app_name);

    Dictionary app_data = get_cache()[p_app_name];
    if (!app_data.has(p_section)) {
        app_data[p_section] = Dictionary();
    }
    Dictionary section = app_data[p_section];
    section[p_key] = p_value;
    app_data[p_section] = section;
    get_cache()[p_app_name] = app_data;

    // Auto-flush to disk
    flush_to_disk(p_app_name);

    UtilityFunctions::print("[VGSettings] Saved: ", p_app_name, "/", p_section, "/", p_key, " = ", p_value);
}

String VGSettings::get_setting(const String &p_app_name, const String &p_section,
                                const String &p_key, const String &p_default) {
    ensure_loaded(p_app_name);

    Dictionary app_data = get_cache()[p_app_name];
    if (!app_data.has(p_section)) return p_default;

    Dictionary section = app_data[p_section];
    if (!section.has(p_key)) return p_default;

    return section[p_key];
}

void VGSettings::delete_setting(const String &p_app_name, const String &p_section,
                                 const String &p_key) {
    ensure_loaded(p_app_name);

    Dictionary app_data = get_cache()[p_app_name];

    if (p_section.is_empty()) {
        // Delete entire app settings
        get_cache().erase(p_app_name);
        // Delete the file
        String ini_path = get_ini_path(p_app_name);
        Ref<DirAccess> d = DirAccess::open(get_settings_dir());
        if (d.is_valid()) {
            d->remove(p_app_name + String(".ini"));
        }
        return;
    }

    if (p_key.is_empty()) {
        // Delete entire section
        app_data.erase(p_section);
    } else {
        // Delete specific key
        if (app_data.has(p_section)) {
            Dictionary section = app_data[p_section];
            section.erase(p_key);
            app_data[p_section] = section;
        }
    }

    get_cache()[p_app_name] = app_data;
    flush_to_disk(p_app_name);
}

Array VGSettings::get_all_settings(const String &p_app_name, const String &p_section) {
    ensure_loaded(p_app_name);

    Array result;
    Dictionary app_data = get_cache()[p_app_name];
    if (!app_data.has(p_section)) return result;

    Dictionary section = app_data[p_section];
    Array keys = section.keys();
    for (int i = 0; i < keys.size(); i++) {
        Array pair;
        pair.push_back(keys[i]);
        pair.push_back(section[keys[i]]);
        result.push_back(pair);
    }
    return result;
}

Dictionary VGSettings::get_section(const String &p_app_name, const String &p_section) {
    ensure_loaded(p_app_name);
    Dictionary app_data = get_cache()[p_app_name];
    if (!app_data.has(p_section)) return Dictionary();
    return app_data[p_section];
}

Array VGSettings::get_sections(const String &p_app_name) {
    ensure_loaded(p_app_name);
    Dictionary app_data = get_cache()[p_app_name];
    return app_data.keys();
}

bool VGSettings::has_setting(const String &p_app_name, const String &p_section, const String &p_key) {
    ensure_loaded(p_app_name);
    Dictionary app_data = get_cache()[p_app_name];
    if (!app_data.has(p_section)) return false;
    Dictionary section = app_data[p_section];
    return section.has(p_key);
}

void VGSettings::flush() {
    Array apps = get_cache().keys();
    for (int i = 0; i < apps.size(); i++) {
        flush_to_disk(apps[i]);
    }
    UtilityFunctions::print("[VGSettings] Flushed all settings to disk");
}
